In [1]:
import pandas as pd

# dictionary, key=file name value=its dataframe
datasets = {}

#7 files, relative file path
datasets["assessments"] = pd.read_csv("../data/raw/assessments.csv")
datasets["courses"] = pd.read_csv("../data/raw/courses.csv")
datasets["student_assessment"] = pd.read_csv("../data/raw/studentAssessment.csv")
datasets["student_info"] = pd.read_csv("../data/raw/studentInfo.csv")
datasets["student_registration"] = pd.read_csv("../data/raw/studentRegistration.csv")
datasets["student_vle"] = pd.read_csv("../data/raw/studentVle.csv")
datasets["vle"] = pd.read_csv("../data/raw/vle.csv")

In [2]:
print(datasets["assessments"].sample(5))

    code_module code_presentation  id_assessment assessment_type   date  \
54          CCC             2014B          24286             CMA   18.0
36          BBB             2014B          15015             CMA   47.0
183         GGG             2013J          37416             TMA  124.0
48          BBB             2014J          15020             TMA   19.0
126         FFF             2013B          34867             CMA  222.0

     weight
54      2.0
36      1.0
183     0.0
48      0.0
126     0.0

In [3]:
print(datasets["courses"].sample(5))

   code_module code_presentation  module_presentation_length
2          BBB             2013J                         268
6          CCC             2014J                         269
14         EEE             2014B                         241
1          AAA             2014J                         269
15         FFF             2013J                         268

In [4]:
print(datasets["student_assessment"].sample(5))

        id_assessment  id_student  date_submitted  is_banked  score
74951           25346     2540922             173          0   53.0
137089          34891      136944             486          0   93.0
85487           25357      632305              74          0   79.0
172736          37441      633818             200          0  100.0
51021           24287      189428              69          0   89.0

In [5]:
print(datasets["student_info"].sample(5));

      code_module code_presentation  id_student gender                region  \
21967         EEE             2014J      680804      M     South West Region
20946         EEE             2014B      629500      M     South East Region
10619         CCC             2014J       69494      F      Yorkshire Region
16125         DDD             2013J     1679727      M              Scotland
6983          BBB             2014J      593346      F  North Western Region

           highest_education imd_band age_band  num_of_prev_attempts  \
21967       HE Qualification   40-50%     0-35                     0
20946  A Level or Equivalent   80-90%     0-35                     0
10619        No Formal quals   20-30%     0-35                     1
16125  A Level or Equivalent   80-90%    35-55                     0
6983      Lower Than A Level    0-10%    35-55                     0

       studied_credits disability final_result
21967               60          N         Pass
20946               60          N         Fail
10619              150          N    Withdrawn
16125               60          N         Pass
6983                60          N         Pass

In [6]:
print(datasets["student_registration"].sample(5))

      code_module code_presentation  id_student  date_registration  \
12529         CCC             2014J      679539              -87.0
2550          BBB             2013J       78255             -162.0
14374         DDD             2013B     2659756              -94.0
30368         GGG             2013J      578940              -29.0
7467          BBB             2014J      648985             -140.0

       date_unregistration
12529                  NaN
2550                  46.0
14374                  NaN
30368                  NaN
7467                   NaN

In [7]:
print(datasets["student_vle"].sample(5))

        code_module code_presentation  id_student  id_site  date  sum_click
1944415         CCC             2014B      633341   730035    -1          2
9916075         FFF             2014J     2301830   882611   150         36
3463406         DDD             2013B      420388   547272   107          1
4258350         DDD             2013J     1819994   673737   208          1
770757          BBB             2013J      534998   703722    -2          1

In [8]:
print(datasets["vle"].sample(5))

      id_site code_module code_presentation activity_type  week_from  week_to
6201   798770         GGG             2014B      resource        NaN      NaN
405    877070         AAA             2014J     oucontent        NaN      NaN
4855   716434         FFF             2013J          quiz        NaN      NaN
1909   909018         CCC             2014J       forumng        NaN      NaN
6245   798811         GGG             2014B      resource        NaN      NaN

In [9]:
# merging datasets before prepcroessing
# COMMON DATASET IN ALL: courses because it is central to each student/assessment/vle resource

# first merged is student info (demographic) / registration / course info /
# merge key are shared between all, left join used to maintain all student records, will deal with missing later
student_data = datasets["student_info"].merge(datasets["student_registration"], on=["id_student","code_module","code_presentation"], how="left")

student_data = student_data.merge(datasets["courses"], on=["code_module","code_presentation"], how="left")

print(student_data.sample(5))

      code_module code_presentation  id_student gender                region  \
17757         DDD             2014J      371949      M  West Midlands Region
21251         EEE             2014J      466508      M          South Region
6526          BBB             2014J      321450      F                 Wales
25726         FFF             2013J      603030      M                 Wales
13725         DDD             2013B      525128      M                 Wales

        highest_education imd_band age_band  num_of_prev_attempts  \
17757  Lower Than A Level   20-30%     0-35                     0
21251    HE Qualification  90-100%     0-35                     0
6526   Lower Than A Level   40-50%     0-35                     1
25726    HE Qualification   80-90%     0-35                     0
13725  Lower Than A Level   60-70%    35-55                     0

       studied_credits disability final_result  date_registration  \
17757               60          Y         Fail             -127.0
21251               30          N         Pass              -77.0
6526               120          N         Pass              -14.0
25726               60          N         Fail              -53.0
13725               90          N         Fail              -23.0

       date_unregistration  module_presentation_length
17757                  NaN                         262
21251                  NaN                         269
6526                   NaN                         262
25726                  NaN                         268
13725                  NaN                         240

In [10]:
# second merged is student specific assessment data + general assessment info + standard course
assessment_data = datasets["student_assessment"].merge(datasets["assessments"], on="id_assessment", how="left")
assessment_data = assessment_data.merge(datasets["courses"], on=["code_module","code_presentation"], how="left")

print(assessment_data.sample(5))

        id_assessment  id_student  date_submitted  is_banked  score  \
61889           24297      549769             147          0   63.0
121884          34876       29769             131          0   60.0
165832          37426      632989             116          0   73.0
14021           14995      517474             189          0   60.0
59004           24295      483543              21          0  100.0

       code_module code_presentation assessment_type   date  weight  \
61889          CCC             2014J             CMA  144.0     8.0
121884         FFF             2013J             TMA  131.0    25.0
165832         GGG             2014B             TMA  117.0     0.0
14021          BBB             2013B             CMA  187.0     1.0
59004          CCC             2014J             CMA   18.0     2.0

        module_presentation_length
61889                          269
121884                         268
165832                         241
14021                          240
59004                          269

In [11]:
# third merged is student specific VLE data + general VLE info + standard course
vle_data = datasets["student_vle"].merge(datasets["vle"], on=["id_site","code_module","code_presentation"],how="left")
vle_data = vle_data.merge(datasets["courses"], on=["code_module","code_presentation"], how="left")

print(vle_data.sample(5))

        code_module code_presentation  id_student  id_site  date  sum_click  \
5193667         DDD             2014J      681799   813701   201         11
9507778         FFF             2014J     1837138   882547    51         26
9801691         FFF             2014J     2301830   883002   127          1
8096417         FFF             2013J     1992145   716238   159          2
9462749         FFF             2014J      413709   883092    45          5

        activity_type  week_from  week_to  module_presentation_length
5193667      homepage        NaN      NaN                         262
9507778       forumng        NaN      NaN                         269
9801691      resource        NaN      NaN                         269
8096417      homepage        NaN      NaN                         268
9462749       subpage        NaN      NaN                         269

In [12]:
#final dataset is simply the vle resources, needed for final recommendations
resource_data = datasets["vle"].copy()

In [13]:
# wayy more organized, reduced 7 DFs to 4
merged_data = {"student_data": student_data, "assessment_data":assessment_data,"vle_data":vle_data, "resource_data": resource_data}

In [14]:
# handle duplicates, first observe

print("Student data number of duplicates:",merged_data["student_data"].duplicated().sum())
print("Assessment data number of duplicates:",merged_data["assessment_data"].duplicated().sum())
print("VLE data number of duplicates:",merged_data["vle_data"].duplicated().sum())
print("Resource data number of duplicates:",merged_data["resource_data"].duplicated().sum())

Student data number of duplicates: 0
Assessment data number of duplicates: 0
VLE data number of duplicates: 787170
Resource data number of duplicates: 0

In [15]:
# seemsl ike vle has a lot of duplicates, view percentage according to entire dataset 
print("Percentage of duplicates in VLE data", (merged_data["vle_data"].duplicated().sum()/len(merged_data["vle_data"]))*100)

Percentage of duplicates in VLE data 7.387605018357096

In [16]:
# final decision: not dropping VLE duplicates because it indicates possibly real multiple interactions 
# note that documentation on OULAD dataset does not mention duplicates
# will drop student/assessment data for completeness in the official python file, but leaving  VLE to be aggregated for resource interaction

In [17]:
# HANDLING MISSING VALUES

# student data

merged_data["student_data"].isna().sum()

code_module                       0
code_presentation                 0
id_student                        0
gender                            0
region                            0
highest_education                 0
imd_band                       1111
age_band                          0
num_of_prev_attempts              0
studied_credits                   0
disability                        0
final_result                      0
date_registration                45
date_unregistration           22521
module_presentation_length        0
dtype: int64

In [18]:
merged_data["student_data"]["imd_band"].mode()

0    20-30%
Name: imd_band, dtype: str

In [19]:
#  for imd band, will fill with mode because it is categorical data and it does not introduce bias
merged_data["student_data"]["imd_band"] = merged_data["student_data"]["imd_band"].fillna(merged_data["student_data"]["imd_band"].mode()[0])

In [20]:
merged_data["student_data"].isna().sum()

code_module                       0
code_presentation                 0
id_student                        0
gender                            0
region                            0
highest_education                 0
imd_band                          0
age_band                          0
num_of_prev_attempts              0
studied_credits                   0
disability                        0
final_result                      0
date_registration                45
date_unregistration           22521
module_presentation_length        0
dtype: int64

In [21]:
# for date registration, will drop because its only 45 records
merged_data["student_data"] = merged_data["student_data"].dropna(subset=['date_registration'])

merged_data["student_data"].isna().sum()

code_module                       0
code_presentation                 0
id_student                        0
gender                            0
region                            0
highest_education                 0
imd_band                          0
age_band                          0
num_of_prev_attempts              0
studied_credits                   0
disability                        0
final_result                      0
date_registration                 0
date_unregistration           22515
module_presentation_length        0
dtype: int64

In [22]:
# from research paper on dataset: 
# Students, who completed the course have this field empty. 
# Students who unregistered have Withdrawal as the value of the final_result in the studentInfo table.

# solution: create separate column with withdrawn boolean flag and fill date unregistration with the module length
merged_data["student_data"]["withdrew"] = merged_data["student_data"]["final_result"] == "Withdrawn"
merged_data["student_data"]["date_unregistration"] = merged_data["student_data"]["date_unregistration"].fillna(merged_data["student_data"]["module_presentation_length"])

In [23]:
merged_data["student_data"].isna().sum()

code_module                   0
code_presentation             0
id_student                    0
gender                        0
region                        0
highest_education             0
imd_band                      0
age_band                      0
num_of_prev_attempts          0
studied_credits               0
disability                    0
final_result                  0
date_registration             0
date_unregistration           0
module_presentation_length    0
withdrew                      0
dtype: int64

In [24]:
#next dataset to handle missing: assessment_data
merged_data["assessment_data"].isna().sum()

id_assessment                    0
id_student                       0
date_submitted                   0
is_banked                        0
score                          173
code_module                      0
code_presentation                0
assessment_type                  0
date                          2865
weight                           0
module_presentation_length       0
dtype: int64

In [25]:
# score will be dropped, very few records and risky to introduce bias in important feature
merged_data["assessment_data"] = merged_data["assessment_data"].dropna(subset=['score'])

In [26]:
merged_data["assessment_data"].isna().sum()

id_assessment                    0
id_student                       0
date_submitted                   0
is_banked                        0
score                            0
code_module                      0
code_presentation                0
assessment_type                  0
date                          2865
weight                           0
module_presentation_length       0
dtype: int64

In [27]:
#for missing dates, according to paper:
#If the information about the final exam cut-off day is missing, it takes place during the last week of the module-presentation.
merged_data["assessment_data"]["date"] = merged_data["assessment_data"]["date"].fillna(merged_data["assessment_data"]["module_presentation_length"]-7)

In [28]:
merged_data["assessment_data"].isna().sum()

id_assessment                 0
id_student                    0
date_submitted                0
is_banked                     0
score                         0
code_module                   0
code_presentation             0
assessment_type               0
date                          0
weight                        0
module_presentation_length    0
dtype: int64

In [29]:
#vle data for missing
merged_data["vle_data"].isna().sum()

code_module                         0
code_presentation                   0
id_student                          0
id_site                             0
date                                0
sum_click                           0
activity_type                       0
week_from                     9269544
week_to                       9269544
module_presentation_length          0
dtype: int64

In [30]:
# large nubmer of week from/to missing, will remove columns entirely as they are not critical to recommendation
merged_data["vle_data"] = merged_data["vle_data"].drop(columns=['week_from','week_to'])

In [31]:
merged_data["vle_data"].isna().sum()

code_module                   0
code_presentation             0
id_student                    0
id_site                       0
date                          0
sum_click                     0
activity_type                 0
module_presentation_length    0
dtype: int64

In [32]:
#last dataset for missing resources
merged_data["resource_data"].isna().sum()

id_site                 0
code_module             0
code_presentation       0
activity_type           0
week_from            5243
week_to              5243
dtype: int64

In [33]:
# large nubmer of week from/to missing, will remove columns entirely as they are not critical to recommendation
merged_data["resource_data"] = merged_data["resource_data"].drop(columns=['week_from','week_to'])

In [34]:
merged_data["resource_data"].isna().sum()

id_site              0
code_module          0
code_presentation    0
activity_type        0
dtype: int64

In [35]:
# next is fixing data types by typecasting

merged_data["student_data"].dtypes

code_module                       str
code_presentation                 str
id_student                      int64
gender                            str
region                            str
highest_education                 str
imd_band                          str
age_band                          str
num_of_prev_attempts            int64
studied_credits                 int64
disability                        str
final_result                      str
date_registration             float64
date_unregistration           float64
module_presentation_length      int64
withdrew                         bool
dtype: object

In [36]:
# convert categories columns:
student_categorical_columns = ["code_module","code_presentation","gender","region","highest_education","imd_band","age_band","final_result"]

for column in student_categorical_columns:
    merged_data["student_data"][column] = merged_data["student_data"][column].astype("category")

In [37]:
#convert booleans
merged_data["student_data"]["withdrew"] = merged_data["student_data"]["withdrew"].astype(bool)

#code inspiration from :https://stackoverflow.com/questions/43897296/pandas-converting-yes-no-to-true-false-failing
# replace y/n with true/false before typecast
merged_data["student_data"] =merged_data["student_data"].replace({'disability': {'Y': True, 'N': False}})
#end inspired code

merged_data["student_data"]["disability"] = merged_data["student_data"]["disability"].astype(bool)

In [38]:
#final data types
merged_data["student_data"].dtypes

code_module                   category
code_presentation             category
id_student                       int64
gender                        category
region                        category
highest_education             category
imd_band                      category
age_band                      category
num_of_prev_attempts             int64
studied_credits                  int64
disability                        bool
final_result                  category
date_registration              float64
date_unregistration            float64
module_presentation_length       int64
withdrew                          bool
dtype: object

In [39]:
#second is assessment data
merged_data["assessment_data"].dtypes

id_assessment                   int64
id_student                      int64
date_submitted                  int64
is_banked                       int64
score                         float64
code_module                       str
code_presentation                 str
assessment_type                   str
date                          float64
weight                        float64
module_presentation_length      int64
dtype: object

In [40]:
# convert categories columns:
assessment_categorical_columns = ["code_module","code_presentation","assessment_type"]

for column in assessment_categorical_columns:
    merged_data["assessment_data"][column] = merged_data["assessment_data"][column].astype("category")

In [41]:
#convert boolean
merged_data["assessment_data"]["is_banked"] = merged_data["assessment_data"]["is_banked"].astype(bool)

In [42]:
# final data types
merged_data["assessment_data"].dtypes

id_assessment                    int64
id_student                       int64
date_submitted                   int64
is_banked                         bool
score                          float64
code_module                   category
code_presentation             category
assessment_type               category
date                           float64
weight                         float64
module_presentation_length       int64
dtype: object

In [43]:
# vle data to typecast
merged_data["vle_data"].dtypes

code_module                     str
code_presentation               str
id_student                    int64
id_site                       int64
date                          int64
sum_click                     int64
activity_type                   str
module_presentation_length    int64
dtype: object

In [44]:
merged_data["vle_data"].sample(5)

,code_module,code_presentation,id_student,id_site,date,sum_click,activity_type,module_presentation_length
2479401,CCC,2014J,685289,909231,4,1,subpage,269
10636598,GGG,2014J,624767,896948,204,1,quiz,269
3242925,DDD,2013B,560114,547303,18,16,homepage,240
6578476,FFF,2013B,107162,526721,41,3,homepage,240
6466036,FFF,2013B,319563,527218,19,1,subpage,240

In [45]:
# convert categories columns:
vle_categorical_columns = ["code_module","code_presentation","activity_type"]

for column in vle_categorical_columns:
    merged_data["vle_data"][column] = merged_data["vle_data"][column].astype("category")

In [46]:
#vle final data types
merged_data["vle_data"].dtypes

code_module                   category
code_presentation             category
id_student                       int64
id_site                          int64
date                             int64
sum_click                        int64
activity_type                 category
module_presentation_length       int64
dtype: object

In [47]:
#resources data types
merged_data["resource_data"].dtypes

id_site              int64
code_module            str
code_presentation      str
activity_type          str
dtype: object

In [48]:
# convert categories columns:
resource_categorical_columns = ["code_module","code_presentation","activity_type"]

for column in resource_categorical_columns:
    merged_data["resource_data"][column] = merged_data["resource_data"][column].astype("category")

In [49]:
#final resources data types
merged_data["resource_data"].dtypes

id_site                 int64
code_module          category
code_presentation    category
activity_type        category
dtype: object

In [50]:
#FEATURE ENGINEERING

In [51]:
#first for student data
merged_data["student_data"].sample(5)

,code_module,code_presentation,id_student,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,disability,final_result,date_registration,date_unregistration,module_presentation_length,withdrew
8983,CCC,2014B,399863,M,West Midlands Region,A Level or Equivalent,30-40%,0-35,0,270,False,Withdrawn,-246.0,-232.0,241,True
1561,BBB,2013B,530065,F,Yorkshire Region,A Level or Equivalent,70-80%,35-55,0,180,False,Pass,-120.0,240.0,240,False
21458,EEE,2014J,620782,M,West Midlands Region,A Level or Equivalent,50-60%,0-35,0,150,False,Pass,-22.0,269.0,269,False
150,AAA,2013J,324282,M,South East Region,A Level or Equivalent,90-100%,0-35,0,120,False,Pass,-32.0,268.0,268,False
12965,CCC,2014J,2172136,M,East Midlands Region,A Level or Equivalent,50-60%,0-35,0,60,False,Distinction,-70.0,269.0,269,False

In [52]:
#obtain registration duration
merged_data["student_data"]["registration_duration"] = merged_data["student_data"]["date_unregistration"] - merged_data["student_data"]["date_registration"]

In [53]:
#for assessment
merged_data["assessment_data"].sample(5)

,id_assessment,id_student,date_submitted,is_banked,score,code_module,code_presentation,assessment_type,date,weight,module_presentation_length
43853,15023,687122,151,False,52.0,BBB,2014J,TMA,152.0,35.0,262
15872,14996,610780,18,False,72.0,BBB,2013J,TMA,19.0,5.0,268
64830,24299,80868,244,False,70.0,CCC,2014J,Exam,262.0,100.0,269
112812,34868,428979,223,False,86.0,FFF,2013B,CMA,222.0,0.0,240
3873,14984,525501,16,False,80.0,BBB,2013B,TMA,19.0,5.0,240

In [54]:
#average score of student for course across all assessments
average_scores = merged_data["assessment_data"].groupby(["id_student", "code_module","code_presentation"])["score"].mean()

#will rename index so that its clear when merged with final df
average_scores = average_scores.reset_index(name="average_score")

In [55]:
average_scores.sample(5)

       id_student code_module code_presentation  average_score
12088      582460         BBB             2014J      73.200000
14254      599398         FFF             2014B      79.750000
13307      592290         BBB             2013J      74.363636
3406       370307         BBB             2013J      81.500000
6738       511949         DDD             2013B      73.888889

In [56]:
merged_data["assessment_data"][merged_data["assessment_data"]["id_student"] ==575112]

,id_assessment,id_student,date_submitted,is_banked,score,code_module,code_presentation,assessment_type,date,weight,module_presentation_length
142549,34899,575112,23,False,84.0,FFF,2014J,TMA,24.0,12.5,269
144728,34900,575112,50,False,72.0,FFF,2014J,TMA,52.0,12.5,269
146849,34901,575112,91,False,88.0,FFF,2014J,TMA,94.0,25.0,269
147359,34902,575112,135,False,86.0,FFF,2014J,TMA,136.0,25.0,269
148913,34903,575112,197,False,93.0,FFF,2014J,TMA,199.0,25.0,269
150740,34904,575112,65,False,91.0,FFF,2014J,CMA,241.0,0.0,269
151259,34905,575112,107,False,89.0,FFF,2014J,CMA,241.0,0.0,269
152901,34906,575112,132,False,68.0,FFF,2014J,CMA,241.0,0.0,269
154664,34907,575112,156,False,91.0,FFF,2014J,CMA,241.0,0.0,269
155106,34908,575112,170,False,75.0,FFF,2014J,CMA,241.0,0.0,269
156592,34909,575112,226,False,78.0,FFF,2014J,CMA,241.0,0.0,269
158297,34910,575112,177,False,88.0,FFF,2014J,CMA,241.0,0.0,269

In [57]:
# simply verifying that it works
merged_data["assessment_data"][merged_data["assessment_data"]["id_student"] ==575112]["score"].mean()

np.float64(83.58333333333333)

In [58]:
#merge with final
merged_data["assessment_data"] = merged_data["assessment_data"].merge(average_scores, on=["id_student", "code_module","code_presentation"],how="left")

In [59]:
merged_data["assessment_data"].sample(5)

,id_assessment,id_student,date_submitted,is_banked,score,code_module,code_presentation,assessment_type,date,weight,module_presentation_length,average_score
73208,25344,406056,117,False,80.0,DDD,2013B,CMA,114.0,4.0,240,70.142857
85917,25358,540758,115,False,80.0,DDD,2014B,TMA,116.0,20.0,241,72.714286
16749,14997,543418,42,False,69.0,BBB,2013J,TMA,47.0,18.0,268,65.833333
134164,34887,630177,52,False,84.0,FFF,2014B,TMA,52.0,12.5,241,93.416667
164650,37425,617909,51,False,56.0,GGG,2014B,TMA,61.0,0.0,241,80.111111

In [60]:
# third is resource data

#resource text used for content based filtering
merged_data["vle_data"].sample(5)

,code_module,code_presentation,id_student,id_site,date,sum_click,activity_type,module_presentation_length
7298454,FFF,2013J,597199,716440,2,1,quiz,268
9231463,FFF,2014J,655127,882993,11,1,resource,269
428939,BBB,2013B,527164,543065,17,1,subpage,240
1512148,BBB,2014J,522189,913696,1,1,subpage,262
817022,BBB,2013J,554540,703732,13,3,forumng,268

In [61]:
merged_data["resource_data"]["resource_text"] = merged_data["vle_data"]["code_module"].astype(str) + " " + merged_data["vle_data"]["code_presentation"].astype(str) + " " + merged_data["vle_data"]["activity_type"].astype(str)

In [62]:
merged_data["resource_data"].sample(5)

      id_site code_module code_presentation activity_type        resource_text
3524   813966         DDD             2014J       subpage   AAA 2013J dataplus
1437   913617         BBB             2014J      resource   AAA 2013J resource
5256   779746         FFF             2014B           url    AAA 2013J subpage
2923   773347         DDD             2014B      resource   AAA 2013J homepage
873    704008         BBB             2013J      resource  AAA 2013J oucontent

In [63]:
#FINAL PREPROCESSING: create resource interaction df for VLE interaction aggregation (so total dfs used will be 5)

In [64]:
merged_data["vle_data"].sample(5)

,code_module,code_presentation,id_student,id_site,date,sum_click,activity_type,module_presentation_length
9554773,FFF,2014J,648140,882537,61,1,homepage,269
5299954,EEE,2013J,2657915,551065,-6,2,oucontent,268
2715709,CCC,2014J,579583,909092,65,1,quiz,269
5272046,DDD,2014J,697101,1016377,238,1,resource,262
8641107,FFF,2014B,402806,779075,51,4,forumng,241

In [65]:
#code inspired by: https://www.kaggle.com/code/veenajoe/veena-vit-project-msc-ds-june-2026#4.2-Aggregating-students-based-on-id

#grouped so each row has one student and their intercation with 1 module resource, each aggregation column specifies 
# new columnName =  (column from VLE data used in aggregation, aggregation function)
#main feature used for collaboartive filtering is the total resource clicks
interaction_data = merged_data["vle_data"].groupby(["id_student","code_module","code_presentation","id_site","activity_type"]).agg(total_resource_clicks=("sum_click","sum"),first_used=("date","min"),last_used=("date","max")).reset_index()
#end inspired code

In [66]:
interaction_data.sample(5)

,id_student,code_module,code_presentation,id_site,activity_type,total_resource_clicks,first_used,last_used
130023,241792,FFF,2013J,716829,resource,1,-18,-18
674134,547581,FFF,2013B,526833,oucontent,48,126,159
101183,187435,CCC,2014B,730112,resource,1,127,127
671051,547128,FFF,2014B,779261,quiz,144,56,226
563765,527619,FFF,2013J,716860,url,5,-18,-18

In [67]:
#verifying no missing
interaction_data.isna().sum()

id_student               0
code_module              0
code_presentation        0
id_site                  0
activity_type            0
total_resource_clicks    0
first_used               0
last_used                0
dtype: int64

In [68]:
interaction_data.loc[interaction_data['total_resource_clicks'].idxmax()]

id_student                540184
code_module                  BBB
code_presentation          2013B
id_site                   542807
activity_type            forumng
total_resource_clicks       8837
first_used                     0
last_used                    240
Name: 627011, dtype: object

In [69]:
#verifies that id site is globally unique, can use simple user-item matrix for collaborative filtering instead of composite key
interaction_data.groupby("id_site")[["code_module", "code_presentation", "activity_type"]].nunique().max()

code_module          1
code_presentation    1
activity_type        1
dtype: int64

In [70]:
#looking at values for temporal splitting (evaluation)
merged_data["vle_data"].sample(5)

,code_module,code_presentation,id_student,id_site,date,sum_click,activity_type,module_presentation_length
2869426,CCC,2014J,580845,909273,140,1,resource,269
3689216,DDD,2013J,585422,674055,-11,2,subpage,261
8228562,FFF,2013J,529862,716435,204,1,quiz,268
6445865,FFF,2013B,557891,527114,17,1,quiz,240
502792,BBB,2013B,525501,542864,45,8,homepage,240

In [71]:
interaction_data.sample(5)

,id_student,code_module,code_presentation,id_site,activity_type,total_resource_clicks,first_used,last_used
1387138,632389,CCC,2014J,909231,subpage,13,-18,15
1697654,695651,DDD,2014J,814089,resource,1,7,7
5229,33681,DDD,2013J,674151,subpage,1,34,34
1840936,2281483,FFF,2013B,527501,dualpane,2,153,153
634781,541532,FFF,2014J,882667,oucontent,37,86,107

In [72]:
#median number of days, used for cutoff day in temporal splitting
merged_data["vle_data"]["date"].median()

np.float64(86.0)

In [73]:
# max for cross validation max
merged_data["vle_data"]["date"].max()

np.int64(269)

In [87]:
merged_data["vle_data"]["date"].min()

np.int64(-25)

In [74]:
#checking if this needs splitting, as per output no need as it is simply a list of resources
merged_data["resource_data"].sample(5)

      id_site code_module code_presentation activity_type        resource_text
1932   937758         CCC             2014J      resource  AAA 2013J oucontent
5865   882633         FFF             2014J     oucontent   AAA 2013J homepage
4815   716687         FFF             2013J       subpage    AAA 2013J forumng
1377   913517         BBB             2014J     oucontent  AAA 2013J oucontent
3680   814100         DDD             2014J      resource    AAA 2013J subpage

In [75]:
#checking evaluation functions, copied from .py file for further analysis
def temporal_split(vle_data,cutoff_day):

    history_vle = vle_data[vle_data["date"]<=cutoff_day].copy()
    future_vle = vle_data[vle_data["date"]> cutoff_day].copy()

    #SAME AS PREPROCESSING STEP for interaction data
    #code inspired by: https://www.kaggle.com/code/veenajoe/veena-vit-project-msc-ds-june-2026#4.2-Aggregating-students-based-on-id

    #grouped so each row has one student and their intercation with 1 module resource, each aggregation column specifies 
    # new columnName =  (column from VLE data used in aggregation, aggregation function)
    #main feature used for collaboartive filtering is the total resource clicks
    history_interactions = history_vle.groupby(["id_student","code_module","code_presentation","id_site","activity_type"]).agg(total_resource_clicks=("sum_click","sum"),first_used=("date","min"),last_used=("date","max")).reset_index()
    future_interactions = future_vle.groupby(["id_student","code_module","code_presentation","id_site","activity_type"]).agg(total_resource_clicks=("sum_click","sum"),first_used=("date","min"),last_used=("date","max")).reset_index()

   #end inspired code

    #to store in 2 separate variables during evaluaton
    return (history_interactions, future_interactions)

#KEY EVALUATION METRICS, input is pandas series of relevant/recommended id of resources
#code copied from: https://giorgi.tech/blog/offline-metrics-for-recommender-systems/
def precision_k(relevant, recommended,k):
    return len(set(relevant).intersection(recommended[:k])) /k

def recall_k(relevant, recommended, k):
    return len(set(relevant).intersection(recommended[:k])) / len(relevant)

#end copied code

In [76]:
history_interactions, future_interactions = temporal_split(merged_data["vle_data"],86)
evaluated_student = 11391

#items from interactions
history_items = history_interactions[history_interactions["id_student"]==evaluated_student]["id_site"]
future_items = future_interactions[history_interactions["id_student"]==evaluated_student]["id_site"]

#removed used resources in history from future items, as goal is to recommend new items
relevant_items = future_items[~future_items.isin(history_items)].unique()

print(len(relevant_items))

37

/var/folders/lg/2w3dsv0s5ll7bp5v9gm83hm80000gn/T/ipykernel_34677/3326403485.py:6: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  future_items = future_interactions[history_interactions["id_student"]==evaluated_student]["id_site"]

In [77]:
#seeing how many students can be evaluated (before filtering for historical/future interactions)
len(interaction_data["id_student"].unique())

26074

In [78]:
#FOR ML FEATURE ENGINEERING, observe outputs

In [79]:
# cutoff for assessment data
merged_data["assessment_data"][merged_data["assessment_data"]["date_submitted"]<=86]

,id_assessment,id_student,date_submitted,is_banked,score,code_module,code_presentation,assessment_type,date,weight,module_presentation_length,average_score
0,1752,11391,18,False,78.0,AAA,2013J,TMA,19.0,10.0,268,82.000
1,1752,28400,22,False,70.0,AAA,2013J,TMA,19.0,10.0,268,66.400
2,1752,31604,17,False,72.0,AAA,2013J,TMA,19.0,10.0,268,76.000
3,1752,32885,26,False,69.0,AAA,2013J,TMA,19.0,10.0,268,54.400
4,1752,38053,19,False,79.0,AAA,2013J,TMA,19.0,10.0,268,68.000
...,...,...,...,...,...,...,...,...,...,...,...,...
172343,37440,624767,-1,True,100.0,GGG,2014J,CMA,229.0,0.0,269,93.125
172353,37440,631446,-1,True,100.0,GGG,2014J,CMA,229.0,0.0,269,88.250
172544,37441,624767,-1,True,100.0,GGG,2014J,CMA,229.0,0.0,269,93.125
172554,37441,631446,-1,True,100.0,GGG,2014J,CMA,229.0,0.0,269,88.250
173066,37442,624767,-1,True,100.0,GGG,2014J,CMA,229.0,0.0,269,93.125

In [80]:
# for vle data
merged_data["vle_data"][merged_data["vle_data"]["date"]<=86]

,code_module,code_presentation,id_student,id_site,date,sum_click,activity_type,module_presentation_length
0,AAA,2013J,28400,546652,-10,4,forumng,268
1,AAA,2013J,28400,546652,-10,1,forumng,268
2,AAA,2013J,28400,546652,-10,1,forumng,268
3,AAA,2013J,28400,546614,-10,11,homepage,268
4,AAA,2013J,28400,546714,-10,1,oucontent,268
...,...,...,...,...,...,...,...,...
10582483,GGG,2014J,628172,897057,86,1,resource,269
10582484,GGG,2014J,628172,897056,86,1,resource,269
10582485,GGG,2014J,628172,897150,86,1,subpage,269
10582486,GGG,2014J,628172,896943,86,1,homepage,269
10582487,GGG,2014J,358341,896943,86,1,homepage,269

In [81]:
#no need cut off for resource
merged_data["resource_data"]

      id_site code_module code_presentation activity_type        resource_text
0      546943         AAA             2013J      resource    AAA 2013J forumng
1      546712         AAA             2013J     oucontent    AAA 2013J forumng
2      546998         AAA             2013J      resource    AAA 2013J forumng
3      546888         AAA             2013J           url   AAA 2013J homepage
4      547035         AAA             2013J      resource  AAA 2013J oucontent
...       ...         ...               ...           ...                  ...
6359   897063         GGG             2014J      resource  AAA 2013J oucontent
6360   897109         GGG             2014J      resource  AAA 2013J oucontent
6361   896965         GGG             2014J     oucontent    AAA 2013J forumng
6362   897060         GGG             2014J      resource   AAA 2013J homepage
6363   897100         GGG             2014J      resource  AAA 2013J oucontent

[6364 rows x 5 columns]

In [82]:
# no need cut off for student data
merged_data["student_data"]

,code_module,code_presentation,id_student,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,disability,final_result,date_registration,date_unregistration,module_presentation_length,withdrew,registration_duration
0,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,0,240,False,Pass,-159.0,268.0,268,False,427.0
1,AAA,2013J,28400,F,Scotland,HE Qualification,20-30%,35-55,0,60,False,Pass,-53.0,268.0,268,False,321.0
2,AAA,2013J,30268,F,North Western Region,A Level or Equivalent,30-40%,35-55,0,60,True,Withdrawn,-92.0,12.0,268,True,104.0
3,AAA,2013J,31604,F,South East Region,A Level or Equivalent,50-60%,35-55,0,60,False,Pass,-52.0,268.0,268,False,320.0
4,AAA,2013J,32885,F,West Midlands Region,Lower Than A Level,50-60%,0-35,0,60,False,Pass,-176.0,268.0,268,False,444.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32588,GGG,2014J,2640965,F,Wales,Lower Than A Level,10-20,0-35,0,30,False,Fail,-4.0,269.0,269,False,273.0
32589,GGG,2014J,2645731,F,East Anglian Region,Lower Than A Level,40-50%,35-55,0,30,False,Distinction,-23.0,269.0,269,False,292.0
32590,GGG,2014J,2648187,F,South Region,A Level or Equivalent,20-30%,0-35,0,30,True,Pass,-129.0,269.0,269,False,398.0
32591,GGG,2014J,2679821,F,South East Region,Lower Than A Level,90-100%,35-55,0,30,False,Withdrawn,-49.0,101.0,269,True,150.0
32592,GGG,2014J,2684003,F,Yorkshire Region,HE Qualification,50-60%,35-55,0,30,False,Distinction,-28.0,269.0,269,False,297.0

In [83]:
#no cutoff
interaction_data

,id_student,code_module,code_presentation,id_site,activity_type,total_resource_clicks,first_used,last_used
0,6516,AAA,2014J,877011,forumng,23,204,218
1,6516,AAA,2014J,877012,forumng,305,0,231
2,6516,AAA,2014J,877015,forumng,26,50,231
3,6516,AAA,2014J,877023,forumng,6,0,184
4,6516,AAA,2014J,877025,forumng,91,-22,227
...,...,...,...,...,...,...,...,...
1960491,2698588,BBB,2014J,951619,resource,1,233,233
1960492,2698588,BBB,2014J,951621,resource,3,228,233
1960493,2698588,BBB,2014J,951623,resource,2,231,233
1960494,2698588,BBB,2014J,985230,oucontent,15,200,235
1960495,2698588,BBB,2014J,992243,resource,3,212,223

In [84]:
# according to columns, can create features related to score / submission date / weight via numerical operations like mean/max/min/count
merged_data["assessment_data"]

,id_assessment,id_student,date_submitted,is_banked,score,code_module,code_presentation,assessment_type,date,weight,module_presentation_length,average_score
0,1752,11391,18,False,78.0,AAA,2013J,TMA,19.0,10.0,268,82.000000
1,1752,28400,22,False,70.0,AAA,2013J,TMA,19.0,10.0,268,66.400000
2,1752,31604,17,False,72.0,AAA,2013J,TMA,19.0,10.0,268,76.000000
3,1752,32885,26,False,69.0,AAA,2013J,TMA,19.0,10.0,268,54.400000
4,1752,38053,19,False,79.0,AAA,2013J,TMA,19.0,10.0,268,68.000000
...,...,...,...,...,...,...,...,...,...,...,...,...
173734,37443,527538,227,False,60.0,GGG,2014J,CMA,229.0,0.0,269,73.888889
173735,37443,534672,229,False,100.0,GGG,2014J,CMA,229.0,0.0,269,79.857143
173736,37443,546286,215,False,80.0,GGG,2014J,CMA,229.0,0.0,269,87.250000
173737,37443,546724,230,False,100.0,GGG,2014J,CMA,229.0,0.0,269,81.222222
173738,37443,558486,224,False,80.0,GGG,2014J,CMA,229.0,0.0,269,68.222222

In [85]:
# similar features with vectorized operations for vle_data
merged_data["vle_data"]

,code_module,code_presentation,id_student,id_site,date,sum_click,activity_type,module_presentation_length
0,AAA,2013J,28400,546652,-10,4,forumng,268
1,AAA,2013J,28400,546652,-10,1,forumng,268
2,AAA,2013J,28400,546652,-10,1,forumng,268
3,AAA,2013J,28400,546614,-10,11,homepage,268
4,AAA,2013J,28400,546714,-10,1,oucontent,268
...,...,...,...,...,...,...,...,...
10655275,GGG,2014J,675811,896943,269,3,homepage,269
10655276,GGG,2014J,675578,896943,269,1,homepage,269
10655277,GGG,2014J,654064,896943,269,3,homepage,269
10655278,GGG,2014J,654064,896939,269,1,forumng,269
10655279,GGG,2014J,654064,896939,269,1,forumng,269

In [86]:
#max number of days, used for cutoff day in temporal splitting (will do 150 for testing data to have enough for future vle)
merged_data["vle_data"]["date"].max()

np.int64(269)