In [1]:
import pandas as pd

# dictionary, key=file name value=its dataframe
datasets = {}

#7 files, relative file path
datasets["assessments"] = pd.read_csv("../data/raw/assessments.csv")
datasets["courses"] = pd.read_csv("../data/raw/courses.csv")
datasets["student_assessment"] = pd.read_csv("../data/raw/studentAssessment.csv")
datasets["student_info"] = pd.read_csv("../data/raw/studentInfo.csv")
datasets["student_registration"] = pd.read_csv("../data/raw/studentRegistration.csv")
datasets["student_vle"] = pd.read_csv("../data/raw/studentVle.csv")
datasets["vle"] = pd.read_csv("../data/raw/vle.csv")

In [2]:
print(datasets["assessments"].sample(5))

    code_module code_presentation  id_assessment assessment_type   date  \
152         FFF             2014B          34893             CMA  227.0
188         GGG             2014B          37430             CMA  222.0
119         EEE             2014J          30719             TMA   33.0
167         FFF             2014J          34908             CMA  241.0
198         GGG             2014J          37440             CMA  229.0

     weight
152     0.0
188     0.0
119    16.0
167     0.0
198     0.0

In [3]:
print(datasets["courses"].sample(5))

   code_module code_presentation  module_presentation_length
4          BBB             2013B                         240
1          AAA             2014J                         269
7          CCC             2014B                         241
5          BBB             2014B                         234
14         EEE             2014B                         241

In [4]:
print(datasets["student_assessment"].sample(5))

        id_assessment  id_student  date_submitted  is_banked  score
44514           15023      582040             171          0   85.0
111137          34866      529644              39          0   95.0
15598           14996      597050              17          0   80.0
153214          34906      647399              65          0   87.0
92978           25365      646006             111          0   84.0

In [5]:
print(datasets["student_info"].sample(5));

      code_module code_presentation  id_student gender               region  \
30481         GGG             2013J      586370      F  East Anglian Region
14298         DDD             2013B     2418045      M    South West Region
7381          BBB             2014J      646691      F              Ireland
23086         FFF             2013B      529871      M  East Anglian Region
31101         GGG             2014B      442877      F    South East Region

           highest_education imd_band age_band  num_of_prev_attempts  \
30481     Lower Than A Level   50-60%     0-35                     0
14298  A Level or Equivalent   40-50%    35-55                     1
7381      Lower Than A Level    10-20     0-35                     0
23086  A Level or Equivalent   40-50%     0-35                     1
31101     Lower Than A Level   40-50%    35-55                     0

       studied_credits disability final_result
30481               30          N         Fail
14298              120          N         Pass
7381                60          N         Fail
23086              150          N         Pass
31101               30          Y         Pass

In [6]:
print(datasets["student_registration"].sample(5))

      code_module code_presentation  id_student  date_registration  \
11305         CCC             2014J      555760              -24.0
5271          BBB             2014B      565869              -24.0
6714          BBB             2014J      511424             -109.0
23353         FFF             2013B      546243              -80.0
23107         FFF             2013B      531294              -80.0

       date_unregistration
11305                  NaN
5271                   NaN
6714                 -46.0
23353                 -5.0
23107                  NaN

In [7]:
print(datasets["student_vle"].sample(5))

        code_module code_presentation  id_student  id_site  date  sum_click
3549065         DDD             2013B      281118   547310   145          2
4338309         DDD             2013J      572280   673519   240          3
8270738         FFF             2013J     2487982   716219   218          4
960525          BBB             2013J      582301   703895    83          1
6301104         FFF             2013B      518831   526737    -6         44

In [8]:
print(datasets["vle"].sample(5))

      id_site code_module code_presentation activity_type  week_from  week_to
1717   730060         CCC             2014B      resource        NaN      NaN
1751   729813         CCC             2014B     oucontent        5.0      7.0
5445   779706         FFF             2014B           url        NaN      NaN
5166   779731         FFF             2014B           url       10.0     10.0
1572   923834         CCC             2014B       forumng        NaN      NaN

In [9]:
# merging datasets before prepcroessing
# COMMON DATASET IN ALL: courses because it is central to each student/assessment/vle resource

# first merged is student info (demographic) / registration / course info /
# merge key are shared between all, left join used to maintain all student records, will deal with missing later
student_data = datasets["student_info"].merge(datasets["student_registration"], on=["id_student","code_module","code_presentation"], how="left")

student_data = student_data.merge(datasets["courses"], on=["code_module","code_presentation"], how="left")

print(student_data.sample(5))

      code_module code_presentation  id_student gender                region  \
15619         DDD             2013J      585208      F   East Anglian Region
24419         FFF             2013J      493539      M  East Midlands Region
4634          BBB             2013J     2225190      M          South Region
7675          BBB             2014J      655471      F                 Wales
32348         GGG             2014J      679921      F                 Wales

           highest_education imd_band age_band  num_of_prev_attempts  \
15619  A Level or Equivalent  90-100%     0-35                     0
24419     Lower Than A Level   50-60%     0-35                     0
4634      Lower Than A Level   50-60%     0-35                     0
7675      Lower Than A Level   20-30%     0-35                     0
32348  A Level or Equivalent  90-100%     0-35                     0

       studied_credits disability final_result  date_registration  \
15619               60          Y    Withdrawn             -142.0
24419               60          N         Pass              -52.0
4634                60          N         Fail              -65.0
7675                60          N         Fail              -38.0
32348               30          N         Pass              -64.0

       date_unregistration  module_presentation_length
15619                213.0                         261
24419                  NaN                         268
4634                   NaN                         268
7675                   NaN                         262
32348                  NaN                         269

In [10]:
# second merged is student specific assessment data + general assessment info + standard course
assessment_data = datasets["student_assessment"].merge(datasets["assessments"], on="id_assessment", how="left")
assessment_data = assessment_data.merge(datasets["courses"], on=["code_module","code_presentation"], how="left")

print(assessment_data.sample(5))

        id_assessment  id_student  date_submitted  is_banked  score  \
110306          34865      550287              17          0   89.0
108548          34864      131272             165          0   79.0
37180           15017      635761             119          0   80.0
41605           15021      695205              54          0   66.0
14970           14996      535269              -1          1   74.0

       code_module code_presentation assessment_type   date  weight  \
110306         FFF             2013B             CMA  222.0     0.0
108548         FFF             2013B             TMA  166.0    25.0
37180          BBB             2014B             CMA  117.0     1.0
41605          BBB             2014J             TMA   54.0    10.0
14970          BBB             2013J             TMA   19.0     5.0

        module_presentation_length
110306                         240
108548                         240
37180                          234
41605                          262
14970                          268

In [11]:
# third merged is student specific VLE data + general VLE info + standard course
vle_data = datasets["student_vle"].merge(datasets["vle"], on=["id_site","code_module","code_presentation"],how="left")
vle_data = vle_data.merge(datasets["courses"], on=["code_module","code_presentation"], how="left")

print(vle_data.sample(5))

         code_module code_presentation  id_student  id_site  date  sum_click  \
9980891          FFF             2014J      641309   882584   167         14
6540991          FFF             2013B      533997   526738    33          1
7549617          FFF             2013J      603389   716216    33          1
10521994         GGG             2014B      623335   798682   205         17
7768501          FFF             2013J      309893   716643    77          1

         activity_type  week_from  week_to  module_presentation_length
9980891      oucontent       21.0     21.0                         269
6540991        forumng        NaN      NaN                         240
7549617        forumng        NaN      NaN                         268
10521994     oucontent        NaN      NaN                         241
7768501        subpage        NaN      NaN                         268

In [12]:
#final dataset is simply the vle resources, needed for final recommendations
resource_data = datasets["vle"].copy()

In [13]:
# wayy more organized, reduced 7 DFs to 4
merged_data = {"student_data": student_data, "assessment_data":assessment_data,"vle_data":vle_data, "resource_data": resource_data}

In [14]:
# handle duplicates, first observe

print("Student data number of duplicates:",merged_data["student_data"].duplicated().sum())
print("Assessment data number of duplicates:",merged_data["assessment_data"].duplicated().sum())
print("VLE data number of duplicates:",merged_data["vle_data"].duplicated().sum())
print("Resource data number of duplicates:",merged_data["resource_data"].duplicated().sum())

Student data number of duplicates: 0
Assessment data number of duplicates: 0
VLE data number of duplicates: 787170
Resource data number of duplicates: 0

In [15]:
# seemsl ike vle has a lot of duplicates, view percentage according to entire dataset 
print("Percentage of duplicates in VLE data", (merged_data["vle_data"].duplicated().sum()/len(merged_data["vle_data"]))*100)

Percentage of duplicates in VLE data 7.387605018357096

In [16]:
# final decision: not dropping VLE duplicates because it indicates possibly real multiple interactions 
# note that documentation on OULAD dataset does not mention duplicates
# will drop student/assessment data for completeness in the official python file, but leaving  VLE to be aggregated for resource interaction

In [17]:
# HANDLING MISSING VALUES

# student data

merged_data["student_data"].isna().sum()

code_module                       0
code_presentation                 0
id_student                        0
gender                            0
region                            0
highest_education                 0
imd_band                       1111
age_band                          0
num_of_prev_attempts              0
studied_credits                   0
disability                        0
final_result                      0
date_registration                45
date_unregistration           22521
module_presentation_length        0
dtype: int64

In [18]:
merged_data["student_data"]["imd_band"].mode()

0    20-30%
Name: imd_band, dtype: str

In [19]:
#  for imd band, will fill with mode because it is categorical data and it does not introduce bias
merged_data["student_data"]["imd_band"] = merged_data["student_data"]["imd_band"].fillna(merged_data["student_data"]["imd_band"].mode()[0])

In [20]:
merged_data["student_data"].isna().sum()

code_module                       0
code_presentation                 0
id_student                        0
gender                            0
region                            0
highest_education                 0
imd_band                          0
age_band                          0
num_of_prev_attempts              0
studied_credits                   0
disability                        0
final_result                      0
date_registration                45
date_unregistration           22521
module_presentation_length        0
dtype: int64

In [21]:
# for date registration, will drop because its only 45 records
merged_data["student_data"] = merged_data["student_data"].dropna(subset=['date_registration'])

merged_data["student_data"].isna().sum()

code_module                       0
code_presentation                 0
id_student                        0
gender                            0
region                            0
highest_education                 0
imd_band                          0
age_band                          0
num_of_prev_attempts              0
studied_credits                   0
disability                        0
final_result                      0
date_registration                 0
date_unregistration           22515
module_presentation_length        0
dtype: int64

In [22]:
# from research paper on dataset: 
# Students, who completed the course have this field empty. 
# Students who unregistered have Withdrawal as the value of the final_result in the studentInfo table.

# solution: create separate column with withdrawn boolean flag and fill date unregistration with the module length
merged_data["student_data"]["withdrew"] = merged_data["student_data"]["final_result"] == "Withdrawn"
merged_data["student_data"]["date_unregistration"] = merged_data["student_data"]["date_unregistration"].fillna(merged_data["student_data"]["module_presentation_length"])

In [23]:
merged_data["student_data"].isna().sum()

code_module                   0
code_presentation             0
id_student                    0
gender                        0
region                        0
highest_education             0
imd_band                      0
age_band                      0
num_of_prev_attempts          0
studied_credits               0
disability                    0
final_result                  0
date_registration             0
date_unregistration           0
module_presentation_length    0
withdrew                      0
dtype: int64

In [24]:
#next dataset to handle missing: assessment_data
merged_data["assessment_data"].isna().sum()

id_assessment                    0
id_student                       0
date_submitted                   0
is_banked                        0
score                          173
code_module                      0
code_presentation                0
assessment_type                  0
date                          2865
weight                           0
module_presentation_length       0
dtype: int64

In [25]:
# score will be dropped, very few records and risky to introduce bias in important feature
merged_data["assessment_data"] = merged_data["assessment_data"].dropna(subset=['score'])

In [26]:
merged_data["assessment_data"].isna().sum()

id_assessment                    0
id_student                       0
date_submitted                   0
is_banked                        0
score                            0
code_module                      0
code_presentation                0
assessment_type                  0
date                          2865
weight                           0
module_presentation_length       0
dtype: int64

In [27]:
#for missing dates, according to paper:
#If the information about the final exam cut-off day is missing, it takes place during the last week of the module-presentation.
merged_data["assessment_data"]["date"] = merged_data["assessment_data"]["date"].fillna(merged_data["assessment_data"]["module_presentation_length"]-7)

In [28]:
merged_data["assessment_data"].isna().sum()

id_assessment                 0
id_student                    0
date_submitted                0
is_banked                     0
score                         0
code_module                   0
code_presentation             0
assessment_type               0
date                          0
weight                        0
module_presentation_length    0
dtype: int64

In [29]:
#vle data for missing
merged_data["vle_data"].isna().sum()

code_module                         0
code_presentation                   0
id_student                          0
id_site                             0
date                                0
sum_click                           0
activity_type                       0
week_from                     9269544
week_to                       9269544
module_presentation_length          0
dtype: int64

In [30]:
# large nubmer of week from/to missing, will remove columns entirely as they are not critical to recommendation
merged_data["vle_data"] = merged_data["vle_data"].drop(columns=['week_from','week_to'])

In [31]:
merged_data["vle_data"].isna().sum()

code_module                   0
code_presentation             0
id_student                    0
id_site                       0
date                          0
sum_click                     0
activity_type                 0
module_presentation_length    0
dtype: int64

In [32]:
#last dataset for missing resources
merged_data["resource_data"].isna().sum()

id_site                 0
code_module             0
code_presentation       0
activity_type           0
week_from            5243
week_to              5243
dtype: int64

In [33]:
# large nubmer of week from/to missing, will remove columns entirely as they are not critical to recommendation
merged_data["resource_data"] = merged_data["resource_data"].drop(columns=['week_from','week_to'])

In [34]:
merged_data["resource_data"].isna().sum()

id_site              0
code_module          0
code_presentation    0
activity_type        0
dtype: int64

In [35]:
# next is fixing data types by typecasting

merged_data["student_data"].dtypes

code_module                       str
code_presentation                 str
id_student                      int64
gender                            str
region                            str
highest_education                 str
imd_band                          str
age_band                          str
num_of_prev_attempts            int64
studied_credits                 int64
disability                        str
final_result                      str
date_registration             float64
date_unregistration           float64
module_presentation_length      int64
withdrew                         bool
dtype: object

In [36]:
# convert categories columns:
student_categorical_columns = ["code_module","code_presentation","gender","region","highest_education","imd_band","age_band","final_result"]

for column in student_categorical_columns:
    merged_data["student_data"][column] = merged_data["student_data"][column].astype("category")

In [37]:
#convert booleans
merged_data["student_data"]["withdrew"] = merged_data["student_data"]["withdrew"].astype(bool)

#code inspiration from :https://stackoverflow.com/questions/43897296/pandas-converting-yes-no-to-true-false-failing
# replace y/n with true/false before typecast
merged_data["student_data"] =merged_data["student_data"].replace({'disability': {'Y': True, 'N': False}})
#end inspired code

merged_data["student_data"]["disability"] = merged_data["student_data"]["disability"].astype(bool)

In [38]:
#final data types
merged_data["student_data"].dtypes

code_module                   category
code_presentation             category
id_student                       int64
gender                        category
region                        category
highest_education             category
imd_band                      category
age_band                      category
num_of_prev_attempts             int64
studied_credits                  int64
disability                        bool
final_result                  category
date_registration              float64
date_unregistration            float64
module_presentation_length       int64
withdrew                          bool
dtype: object

In [39]:
#second is assessment data
merged_data["assessment_data"].dtypes

id_assessment                   int64
id_student                      int64
date_submitted                  int64
is_banked                       int64
score                         float64
code_module                       str
code_presentation                 str
assessment_type                   str
date                          float64
weight                        float64
module_presentation_length      int64
dtype: object

In [40]:
# convert categories columns:
assessment_categorical_columns = ["code_module","code_presentation","assessment_type"]

for column in assessment_categorical_columns:
    merged_data["assessment_data"][column] = merged_data["assessment_data"][column].astype("category")

In [41]:
#convert boolean
merged_data["assessment_data"]["is_banked"] = merged_data["assessment_data"]["is_banked"].astype(bool)

In [42]:
# final data types
merged_data["assessment_data"].dtypes

id_assessment                    int64
id_student                       int64
date_submitted                   int64
is_banked                         bool
score                          float64
code_module                   category
code_presentation             category
assessment_type               category
date                           float64
weight                         float64
module_presentation_length       int64
dtype: object

In [43]:
# vle data to typecast
merged_data["vle_data"].dtypes

code_module                     str
code_presentation               str
id_student                    int64
id_site                       int64
date                          int64
sum_click                     int64
activity_type                   str
module_presentation_length    int64
dtype: object

In [44]:
merged_data["vle_data"].sample(5)

,code_module,code_presentation,id_student,id_site,date,sum_click,activity_type,module_presentation_length
2880770,CCC,2014J,653452,909020,143,1,forumng,269
5571204,EEE,2013J,555228,551021,154,1,oucontent,268
59707,AAA,2013J,343446,546739,47,2,oucontent,268
2886901,CCC,2014J,560065,909232,144,5,subpage,269
6757974,FFF,2013B,529864,526721,86,5,homepage,240

In [45]:
# convert categories columns:
vle_categorical_columns = ["code_module","code_presentation","activity_type"]

for column in vle_categorical_columns:
    merged_data["vle_data"][column] = merged_data["vle_data"][column].astype("category")

In [46]:
#vle final data types
merged_data["vle_data"].dtypes

code_module                   category
code_presentation             category
id_student                       int64
id_site                          int64
date                             int64
sum_click                        int64
activity_type                 category
module_presentation_length       int64
dtype: object

In [47]:
#resources data types
merged_data["resource_data"].dtypes

id_site              int64
code_module            str
code_presentation      str
activity_type          str
dtype: object

In [48]:
# convert categories columns:
resource_categorical_columns = ["code_module","code_presentation","activity_type"]

for column in resource_categorical_columns:
    merged_data["resource_data"][column] = merged_data["resource_data"][column].astype("category")

In [49]:
#final resources data types
merged_data["resource_data"].dtypes

id_site                 int64
code_module          category
code_presentation    category
activity_type        category
dtype: object

In [50]:
#FEATURE ENGINEERING

In [51]:
#first for student data
merged_data["student_data"].sample(5)

,code_module,code_presentation,id_student,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,disability,final_result,date_registration,date_unregistration,module_presentation_length,withdrew
25443,FFF,2013J,594119,M,East Anglian Region,A Level or Equivalent,40-50%,0-35,0,60,False,Pass,-86.0,268.0,268,False
21193,EEE,2014J,346093,M,Ireland,Post Graduate Qualification,20-30%,0-35,0,30,False,Pass,-49.0,269.0,269,False
15541,DDD,2013J,580415,F,North Western Region,Lower Than A Level,80-90%,0-35,0,120,False,Distinction,-63.0,261.0,261,False
12566,CCC,2014J,682226,M,Scotland,A Level or Equivalent,50-60%,0-35,0,30,False,Withdrawn,-46.0,116.0,269,True
27288,FFF,2014B,628361,M,Scotland,HE Qualification,60-70%,35-55,0,60,False,Distinction,-65.0,241.0,241,False

In [52]:
#obtain registration duration
merged_data["student_data"]["registration_duration"] = merged_data["student_data"]["date_unregistration"] - merged_data["student_data"]["date_registration"]

In [53]:
#for assessment
merged_data["assessment_data"].sample(5)

,id_assessment,id_student,date_submitted,is_banked,score,code_module,code_presentation,assessment_type,date,weight,module_presentation_length
15018,14996,549445,19,False,59.0,BBB,2013J,TMA,19.0,5.0,268
5228,14985,527227,44,False,68.0,BBB,2013B,TMA,47.0,18.0,240
153022,34906,622934,233,False,92.0,FFF,2014J,CMA,241.0,0.0,269
26252,15005,491279,133,False,80.0,BBB,2013J,CMA,131.0,1.0,268
11028,14992,489251,95,False,100.0,BBB,2013B,CMA,89.0,1.0,240

In [54]:
#average score of student for course across all assessments
average_scores = merged_data["assessment_data"].groupby(["id_student", "code_module","code_presentation"])["score"].mean()

#will rename index so that its clear when merged with final df
average_scores = average_scores.reset_index(name="average_score")

In [55]:
average_scores.sample(5)

       id_student code_module code_presentation  average_score
10743      570113         CCC             2014B      40.000000
978        146974         EEE             2013J      75.000000
23025     1031884         DDD             2014B      92.571429
18481      632503         BBB             2014B      93.545455
4097       406416         BBB             2013B      50.000000

In [56]:
merged_data["assessment_data"][merged_data["assessment_data"]["id_student"] ==575112]

,id_assessment,id_student,date_submitted,is_banked,score,code_module,code_presentation,assessment_type,date,weight,module_presentation_length
142549,34899,575112,23,False,84.0,FFF,2014J,TMA,24.0,12.5,269
144728,34900,575112,50,False,72.0,FFF,2014J,TMA,52.0,12.5,269
146849,34901,575112,91,False,88.0,FFF,2014J,TMA,94.0,25.0,269
147359,34902,575112,135,False,86.0,FFF,2014J,TMA,136.0,25.0,269
148913,34903,575112,197,False,93.0,FFF,2014J,TMA,199.0,25.0,269
150740,34904,575112,65,False,91.0,FFF,2014J,CMA,241.0,0.0,269
151259,34905,575112,107,False,89.0,FFF,2014J,CMA,241.0,0.0,269
152901,34906,575112,132,False,68.0,FFF,2014J,CMA,241.0,0.0,269
154664,34907,575112,156,False,91.0,FFF,2014J,CMA,241.0,0.0,269
155106,34908,575112,170,False,75.0,FFF,2014J,CMA,241.0,0.0,269
156592,34909,575112,226,False,78.0,FFF,2014J,CMA,241.0,0.0,269
158297,34910,575112,177,False,88.0,FFF,2014J,CMA,241.0,0.0,269

In [57]:
# simply verifying that it works
merged_data["assessment_data"][merged_data["assessment_data"]["id_student"] ==575112]["score"].mean()

np.float64(83.58333333333333)

In [58]:
#merge with final
merged_data["assessment_data"] = merged_data["assessment_data"].merge(average_scores, on=["id_student", "code_module","code_presentation"],how="left")

In [59]:
merged_data["assessment_data"].sample(5)

,id_assessment,id_student,date_submitted,is_banked,score,code_module,code_presentation,assessment_type,date,weight,module_presentation_length,average_score
97022,30710,573440,65,False,94.0,EEE,2013J,TMA,68.0,28.0,268,91.750000
7628,14987,558075,120,False,77.0,BBB,2013B,TMA,124.0,18.0,240,84.545455
137855,34892,610094,158,False,87.0,FFF,2014B,CMA,227.0,0.0,241,72.916667
77802,25349,590443,51,False,84.0,DDD,2013J,TMA,53.0,12.5,261,81.571429
50385,24287,585093,69,False,100.0,CCC,2014B,CMA,67.0,7.0,241,96.777778

In [60]:
# third is resource data

#resource text used for content based filtering
merged_data["vle_data"].sample(5)

,code_module,code_presentation,id_student,id_site,date,sum_click,activity_type,module_presentation_length
211099,AAA,2014J,2574990,877134,13,9,subpage,269
703074,BBB,2013B,145544,542895,186,1,quiz,240
3745510,DDD,2013J,596846,673746,4,2,ouwiki,261
8153540,FFF,2013J,2197175,716270,173,1,oucontent,268
9608089,FFF,2014J,655127,882638,75,3,oucontent,269

In [61]:
merged_data["resource_data"]["resource_text"] = merged_data["vle_data"]["code_module"].astype(str) + " " + merged_data["vle_data"]["code_presentation"].astype(str) + " " + merged_data["vle_data"]["activity_type"].astype(str)

In [62]:
merged_data["resource_data"].sample(5)

      id_site code_module code_presentation activity_type        resource_text
650    542794         BBB             2013B       forumng  AAA 2013J oucontent
1268   768616         BBB             2014B      resource    AAA 2013J subpage
3291   773366         DDD             2014B      resource   AAA 2013J resource
1207   768334         BBB             2014B       forumng   AAA 2013J resource
5230   779784         FFF             2014B           url   AAA 2013J homepage

In [63]:
#FINAL PREPROCESSING: create resource interaction df for VLE interaction aggregation (so total dfs used will be 5)

In [64]:
merged_data["vle_data"].sample(5)

,code_module,code_presentation,id_student,id_site,date,sum_click,activity_type,module_presentation_length
3818954,DDD,2013J,513853,674110,21,2,subpage,261
5421773,EEE,2013J,597573,551010,49,2,homepage,268
3008544,CCC,2014J,2013403,909338,207,1,url,269
798296,BBB,2013J,388975,703737,7,3,forumng,268
6712709,FFF,2013B,553727,526721,75,1,homepage,240

In [65]:
#code inspired by: https://www.kaggle.com/code/veenajoe/veena-vit-project-msc-ds-june-2026#4.2-Aggregating-students-based-on-id

#grouped so each row has one student and their intercation with 1 module resource, each aggregation column specifies 
# new columnName =  (column from VLE data used in aggregation, aggregation function)
#main feature used for collaboartive filtering is the total resource clicks
interaction_data = merged_data["vle_data"].groupby(["id_student","code_module","code_presentation","id_site","activity_type"]).agg(total_resource_clicks=("sum_click","sum"),first_used=("date","min"),last_used=("date","max")).reset_index()
#end inspired code

In [66]:
interaction_data.sample(5)

,id_student,code_module,code_presentation,id_site,activity_type,total_resource_clicks,first_used,last_used
953841,584443,CCC,2014J,909033,oucontent,1,25,25
1211333,611202,EEE,2013J,551065,oucontent,29,2,4
1674449,691519,GGG,2014J,896943,homepage,211,-2,228
579382,530558,FFF,2013B,527505,dualpane,1,0,0
1821704,2170320,FFF,2013J,716246,oucontent,26,19,19

In [67]:
#verifying no missing
interaction_data.isna().sum()

id_student               0
code_module              0
code_presentation        0
id_site                  0
activity_type            0
total_resource_clicks    0
first_used               0
last_used                0
dtype: int64

In [68]:
interaction_data.loc[interaction_data['total_resource_clicks'].idxmax()]

id_student                540184
code_module                  BBB
code_presentation          2013B
id_site                   542807
activity_type            forumng
total_resource_clicks       8837
first_used                     0
last_used                    240
Name: 627011, dtype: object

In [69]:
#verifies that id site is globally unique, can use simple user-item matrix for collaborative filtering instead of composite key
interaction_data.groupby("id_site")[["code_module", "code_presentation", "activity_type"]].nunique().max()

code_module          1
code_presentation    1
activity_type        1
dtype: int64

In [70]:
#looking at values for temporal splitting (evaluation)
merged_data["vle_data"].sample(5)

,code_module,code_presentation,id_student,id_site,date,sum_click,activity_type,module_presentation_length
1153896,BBB,2013J,490677,703733,209,1,forumng,268
1048077,BBB,2013J,532477,703741,133,6,forumng,268
10025737,FFF,2014J,593796,882620,184,1,oucontent,269
8340754,FFF,2013J,572250,716455,234,2,questionnaire,268
3083404,CCC,2014J,607453,909233,236,2,subpage,269

In [71]:
interaction_data.sample(5)

,id_student,code_module,code_presentation,id_site,activity_type,total_resource_clicks,first_used,last_used
218354,336684,DDD,2013B,547642,resource,2,8,149
1545232,655613,BBB,2014J,913502,oucontent,2,93,93
1900932,2528966,BBB,2013B,543058,subpage,2,123,164
1136709,603224,DDD,2014J,813961,subpage,46,-14,242
534040,519102,DDD,2013B,547930,subpage,8,3,17

In [72]:
#median number of days, used for cutoff day in temporal splitting
merged_data["vle_data"]["date"].median()

np.float64(86.0)

In [73]:
#checking if this needs splitting, as per output no need as it is simply a list of resources
merged_data["resource_data"].sample(5)

      id_site code_module code_presentation activity_type        resource_text
4552   716705         FFF             2013J      resource        AAA 2013J url
2659   674206         DDD             2013J      resource   AAA 2013J homepage
2608   674286         DDD             2013J      resource    AAA 2013J subpage
239    877211         AAA             2014J      resource        AAA 2013J url
5253   779713         FFF             2014B           url  AAA 2013J oucontent

In [74]:
#checking evaluation functions, copied from .py file for further analysis
def temporal_split(vle_data,cutoff_day):

    history_vle = vle_data[vle_data["date"]<=cutoff_day].copy()
    future_vle = vle_data[vle_data["date"]> cutoff_day].copy()

    #SAME AS PREPROCESSING STEP for interaction data
    #code inspired by: https://www.kaggle.com/code/veenajoe/veena-vit-project-msc-ds-june-2026#4.2-Aggregating-students-based-on-id

    #grouped so each row has one student and their intercation with 1 module resource, each aggregation column specifies 
    # new columnName =  (column from VLE data used in aggregation, aggregation function)
    #main feature used for collaboartive filtering is the total resource clicks
    history_interactions = history_vle.groupby(["id_student","code_module","code_presentation","id_site","activity_type"]).agg(total_resource_clicks=("sum_click","sum"),first_used=("date","min"),last_used=("date","max")).reset_index()
    future_interactions = future_vle.groupby(["id_student","code_module","code_presentation","id_site","activity_type"]).agg(total_resource_clicks=("sum_click","sum"),first_used=("date","min"),last_used=("date","max")).reset_index()

   #end inspired code

    #to store in 2 separate variables during evaluaton
    return (history_interactions, future_interactions)

#KEY EVALUATION METRICS, input is pandas series of relevant/recommended id of resources
#code copied from: https://giorgi.tech/blog/offline-metrics-for-recommender-systems/
def precision_k(relevant, recommended,k):
    return len(set(relevant).intersection(recommended[:k])) /k

def recall_k(relevant, recommended, k):
    return len(set(relevant).intersection(recommended[:k])) / len(relevant)

#end copied code

In [75]:
history_interactions, future_interactions = temporal_split(merged_data["vle_data"],86)
evaluated_student = 11391

#items from interactions
history_items = history_interactions[history_interactions["id_student"]==evaluated_student]["id_site"]
future_items = future_interactions[history_interactions["id_student"]==evaluated_student]["id_site"]

#removed used resources in history from future items, as goal is to recommend new items
relevant_items = future_items[~future_items.isin(history_items)].unique()

print(len(relevant_items))

37

/var/folders/lg/2w3dsv0s5ll7bp5v9gm83hm80000gn/T/ipykernel_14480/3326403485.py:6: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  future_items = future_interactions[history_interactions["id_student"]==evaluated_student]["id_site"]

In [76]:
#seeing how many students can be evaluated (before filtering for historical/future interactions)
len(interaction_data["id_student"].unique())

26074

In [77]:
#FOR ML FEATURE ENGINEERING, observe outputs

In [79]:
# cutoff for assessment data
merged_data["assessment_data"][merged_data["assessment_data"]["date_submitted"]<=86]

,id_assessment,id_student,date_submitted,is_banked,score,code_module,code_presentation,assessment_type,date,weight,module_presentation_length,average_score
0,1752,11391,18,False,78.0,AAA,2013J,TMA,19.0,10.0,268,82.000
1,1752,28400,22,False,70.0,AAA,2013J,TMA,19.0,10.0,268,66.400
2,1752,31604,17,False,72.0,AAA,2013J,TMA,19.0,10.0,268,76.000
3,1752,32885,26,False,69.0,AAA,2013J,TMA,19.0,10.0,268,54.400
4,1752,38053,19,False,79.0,AAA,2013J,TMA,19.0,10.0,268,68.000
...,...,...,...,...,...,...,...,...,...,...,...,...
172343,37440,624767,-1,True,100.0,GGG,2014J,CMA,229.0,0.0,269,93.125
172353,37440,631446,-1,True,100.0,GGG,2014J,CMA,229.0,0.0,269,88.250
172544,37441,624767,-1,True,100.0,GGG,2014J,CMA,229.0,0.0,269,93.125
172554,37441,631446,-1,True,100.0,GGG,2014J,CMA,229.0,0.0,269,88.250
173066,37442,624767,-1,True,100.0,GGG,2014J,CMA,229.0,0.0,269,93.125

In [80]:
# for vle data
merged_data["vle_data"][merged_data["vle_data"]["date"]<=86]

,code_module,code_presentation,id_student,id_site,date,sum_click,activity_type,module_presentation_length
0,AAA,2013J,28400,546652,-10,4,forumng,268
1,AAA,2013J,28400,546652,-10,1,forumng,268
2,AAA,2013J,28400,546652,-10,1,forumng,268
3,AAA,2013J,28400,546614,-10,11,homepage,268
4,AAA,2013J,28400,546714,-10,1,oucontent,268
...,...,...,...,...,...,...,...,...
10582483,GGG,2014J,628172,897057,86,1,resource,269
10582484,GGG,2014J,628172,897056,86,1,resource,269
10582485,GGG,2014J,628172,897150,86,1,subpage,269
10582486,GGG,2014J,628172,896943,86,1,homepage,269
10582487,GGG,2014J,358341,896943,86,1,homepage,269

In [81]:
#no need cut off for resource
merged_data["resource_data"]

      id_site code_module code_presentation activity_type        resource_text
0      546943         AAA             2013J      resource    AAA 2013J forumng
1      546712         AAA             2013J     oucontent    AAA 2013J forumng
2      546998         AAA             2013J      resource    AAA 2013J forumng
3      546888         AAA             2013J           url   AAA 2013J homepage
4      547035         AAA             2013J      resource  AAA 2013J oucontent
...       ...         ...               ...           ...                  ...
6359   897063         GGG             2014J      resource  AAA 2013J oucontent
6360   897109         GGG             2014J      resource  AAA 2013J oucontent
6361   896965         GGG             2014J     oucontent    AAA 2013J forumng
6362   897060         GGG             2014J      resource   AAA 2013J homepage
6363   897100         GGG             2014J      resource  AAA 2013J oucontent

[6364 rows x 5 columns]

In [82]:
# no need cut off for student data
merged_data["student_data"]

,code_module,code_presentation,id_student,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,disability,final_result,date_registration,date_unregistration,module_presentation_length,withdrew,registration_duration
0,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,0,240,False,Pass,-159.0,268.0,268,False,427.0
1,AAA,2013J,28400,F,Scotland,HE Qualification,20-30%,35-55,0,60,False,Pass,-53.0,268.0,268,False,321.0
2,AAA,2013J,30268,F,North Western Region,A Level or Equivalent,30-40%,35-55,0,60,True,Withdrawn,-92.0,12.0,268,True,104.0
3,AAA,2013J,31604,F,South East Region,A Level or Equivalent,50-60%,35-55,0,60,False,Pass,-52.0,268.0,268,False,320.0
4,AAA,2013J,32885,F,West Midlands Region,Lower Than A Level,50-60%,0-35,0,60,False,Pass,-176.0,268.0,268,False,444.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32588,GGG,2014J,2640965,F,Wales,Lower Than A Level,10-20,0-35,0,30,False,Fail,-4.0,269.0,269,False,273.0
32589,GGG,2014J,2645731,F,East Anglian Region,Lower Than A Level,40-50%,35-55,0,30,False,Distinction,-23.0,269.0,269,False,292.0
32590,GGG,2014J,2648187,F,South Region,A Level or Equivalent,20-30%,0-35,0,30,True,Pass,-129.0,269.0,269,False,398.0
32591,GGG,2014J,2679821,F,South East Region,Lower Than A Level,90-100%,35-55,0,30,False,Withdrawn,-49.0,101.0,269,True,150.0
32592,GGG,2014J,2684003,F,Yorkshire Region,HE Qualification,50-60%,35-55,0,30,False,Distinction,-28.0,269.0,269,False,297.0

In [84]:
#no cutoff
interaction_data

,id_student,code_module,code_presentation,id_site,activity_type,total_resource_clicks,first_used,last_used
0,6516,AAA,2014J,877011,forumng,23,204,218
1,6516,AAA,2014J,877012,forumng,305,0,231
2,6516,AAA,2014J,877015,forumng,26,50,231
3,6516,AAA,2014J,877023,forumng,6,0,184
4,6516,AAA,2014J,877025,forumng,91,-22,227
...,...,...,...,...,...,...,...,...
1960491,2698588,BBB,2014J,951619,resource,1,233,233
1960492,2698588,BBB,2014J,951621,resource,3,228,233
1960493,2698588,BBB,2014J,951623,resource,2,231,233
1960494,2698588,BBB,2014J,985230,oucontent,15,200,235
1960495,2698588,BBB,2014J,992243,resource,3,212,223

In [85]:
# according to columns, can create features related to score / submission date / weight via numerical operations like mean/max/min/count
merged_data["assessment_data"]

,id_assessment,id_student,date_submitted,is_banked,score,code_module,code_presentation,assessment_type,date,weight,module_presentation_length,average_score
0,1752,11391,18,False,78.0,AAA,2013J,TMA,19.0,10.0,268,82.000000
1,1752,28400,22,False,70.0,AAA,2013J,TMA,19.0,10.0,268,66.400000
2,1752,31604,17,False,72.0,AAA,2013J,TMA,19.0,10.0,268,76.000000
3,1752,32885,26,False,69.0,AAA,2013J,TMA,19.0,10.0,268,54.400000
4,1752,38053,19,False,79.0,AAA,2013J,TMA,19.0,10.0,268,68.000000
...,...,...,...,...,...,...,...,...,...,...,...,...
173734,37443,527538,227,False,60.0,GGG,2014J,CMA,229.0,0.0,269,73.888889
173735,37443,534672,229,False,100.0,GGG,2014J,CMA,229.0,0.0,269,79.857143
173736,37443,546286,215,False,80.0,GGG,2014J,CMA,229.0,0.0,269,87.250000
173737,37443,546724,230,False,100.0,GGG,2014J,CMA,229.0,0.0,269,81.222222
173738,37443,558486,224,False,80.0,GGG,2014J,CMA,229.0,0.0,269,68.222222

In [86]:
# similar features with vectorized operations for vle_data
merged_data["vle_data"]

,code_module,code_presentation,id_student,id_site,date,sum_click,activity_type,module_presentation_length
0,AAA,2013J,28400,546652,-10,4,forumng,268
1,AAA,2013J,28400,546652,-10,1,forumng,268
2,AAA,2013J,28400,546652,-10,1,forumng,268
3,AAA,2013J,28400,546614,-10,11,homepage,268
4,AAA,2013J,28400,546714,-10,1,oucontent,268
...,...,...,...,...,...,...,...,...
10655275,GGG,2014J,675811,896943,269,3,homepage,269
10655276,GGG,2014J,675578,896943,269,1,homepage,269
10655277,GGG,2014J,654064,896943,269,3,homepage,269
10655278,GGG,2014J,654064,896939,269,1,forumng,269
10655279,GGG,2014J,654064,896939,269,1,forumng,269

In [87]:
#max number of days, used for cutoff day in temporal splitting (will do 150 for testing data to have enough for future vle)
merged_data["vle_data"]["date"].max()

np.int64(269)