In [1]:
import pandas as pd

# dictionary, key=file name value=its dataframe
datasets = {}

#7 files, relative file path
datasets["assessments"] = pd.read_csv("../data/raw/assessments.csv")
datasets["courses"] = pd.read_csv("../data/raw/courses.csv")
datasets["student_assessment"] = pd.read_csv("../data/raw/studentAssessment.csv")
datasets["student_info"] = pd.read_csv("../data/raw/studentInfo.csv")
datasets["student_registration"] = pd.read_csv("../data/raw/studentRegistration.csv")
datasets["student_vle"] = pd.read_csv("../data/raw/studentVle.csv")
datasets["vle"] = pd.read_csv("../data/raw/vle.csv")

In [2]:
print(datasets["assessments"].sample(5))

    code_module code_presentation  id_assessment assessment_type   date  \
131         FFF             2013B          34860             TMA   19.0
115         EEE             2014B          30715             TMA   68.0
146         FFF             2013J          34875             TMA   96.0
102         DDD             2014J          25362             TMA   20.0
112         EEE             2013J          30712             TMA  159.0

     weight
131    12.5
115    28.0
146    25.0
102     5.0
112    28.0

In [3]:
print(datasets["courses"].sample(5))

   code_module code_presentation  module_presentation_length
0          AAA             2013J                         268
3          BBB             2014J                         262
4          BBB             2013B                         240
14         EEE             2014B                         241
6          CCC             2014J                         269

In [4]:
print(datasets["student_assessment"].sample(5))

        id_assessment  id_student  date_submitted  is_banked  score
96792           30709      554235              28          0   74.0
149919          34904      677748              62          0   72.0
172358          37440      693364             193          0   80.0
92728           25365      585526             125          0   76.0
107401          34862      551796              95          0   95.0

In [5]:
print(datasets["student_info"].sample(5));

      code_module code_presentation  id_student gender               region  \
8471          BBB             2014J      699488      F                Wales
31377         GGG             2014B      617133      F         South Region
3590          BBB             2013J      575207      M  East Anglian Region
12807         CCC             2014J      696848      M         North Region
31589         GGG             2014B      628189      M    South East Region

                 highest_education imd_band age_band  num_of_prev_attempts  \
8471         A Level or Equivalent   20-30%    35-55                     0
31377           Lower Than A Level   40-50%     0-35                     0
3590            Lower Than A Level    10-20    35-55                     0
12807  Post Graduate Qualification      NaN     0-35                     0
31589           Lower Than A Level   30-40%    35-55                     0

       studied_credits disability final_result
8471               120          N  Distinction
31377               30          Y         Fail
3590               120          N    Withdrawn
12807              120          N    Withdrawn
31589               90          N         Fail

In [6]:
print(datasets["student_registration"].sample(5))

      code_module code_presentation  id_student  date_registration  \
26229         FFF             2014B      106747             -124.0
21645         EEE             2014J      647791             -147.0
16726         DDD             2014B      552003             -137.0
27902         FFF             2014J      349777              -68.0
19053         DDD             2014J      690669               -9.0

       date_unregistration
26229                -51.0
21645                 12.0
16726                  NaN
27902                 51.0
19053                101.0

In [7]:
print(datasets["student_vle"].sample(5))

        code_module code_presentation  id_student  id_site  date  sum_click
1417810         BBB             2014B      631561   768393   153          1
8863256         FFF             2014B      622976   779354   139         14
6772261         FFF             2013B      533535   527179    88          7
2213990         CCC             2014B      266558   729671   111          1
9044241         FFF             2014B      633077   779645   226          2

In [8]:
print(datasets["vle"].sample(5))

      id_site code_module code_presentation activity_type  week_from  week_to
3571  1016372         DDD             2014J       forumng        NaN      NaN
2393   547894         DDD             2013B       subpage        NaN      NaN
5508   779536         FFF             2014B      resource       28.0     28.0
4101   526855         FFF             2013B     oucontent        1.0      1.0
4210   527252         FFF             2013B           url        NaN      NaN

In [9]:
# merging datasets before prepcroessing
# COMMON DATASET IN ALL: courses because it is central to each student/assessment/vle resource

# first merged is student info (demographic) / registration / course info /
# merge key are shared between all, left join used to maintain all student records, will deal with missing later
student_data = datasets["student_info"].merge(datasets["student_registration"], on=["id_student","code_module","code_presentation"], how="left")

student_data = student_data.merge(datasets["courses"], on=["code_module","code_presentation"], how="left")

print(student_data.sample(5))

      code_module code_presentation  id_student gender                region  \
16265         DDD             2013J     2550054      F  North Western Region
7243          BBB             2014J      635924      F   East Anglian Region
16918         DDD             2014B      605759      M  East Midlands Region
25085         FFF             2013J      580709      M          South Region
8608          BBB             2014J     2497624      F              Scotland

           highest_education imd_band age_band  num_of_prev_attempts  \
16265       HE Qualification   50-60%    35-55                     0
7243   A Level or Equivalent   40-50%     0-35                     0
16918  A Level or Equivalent   50-60%     0-35                     0
25085  A Level or Equivalent    10-20     0-35                     0
8608      Lower Than A Level   60-70%    35-55                     0

       studied_credits disability final_result  date_registration  \
16265               60          N         Fail             -100.0
7243                60          N         Pass              -22.0
16918               90          N    Withdrawn              -90.0
25085               60          N         Pass             -130.0
8608               120          Y         Pass              -49.0

       date_unregistration  module_presentation_length
16265                  NaN                         261
7243                   NaN                         262
16918                226.0                         241
25085                  NaN                         268
8608                   NaN                         262

In [10]:
# second merged is student specific assessment data + general assessment info + standard course
assessment_data = datasets["student_assessment"].merge(datasets["assessments"], on="id_assessment", how="left")
assessment_data = assessment_data.merge(datasets["courses"], on=["code_module","code_presentation"], how="left")

print(assessment_data.sample(5))

        id_assessment  id_student  date_submitted  is_banked  score  \
21977           15001       73489             206          0   64.0
161181          37418      593819             122          0  100.0
13412           14994      555670             164          0  100.0
21599           15001      591420             208          0   74.0
102949          30721      680267             131          0   69.0

       code_module code_presentation assessment_type   date  weight  \
21977          BBB             2013J             TMA  208.0    18.0
161181         GGG             2013J             CMA  229.0     0.0
13412          BBB             2013B             CMA  159.0     1.0
21599          BBB             2013J             TMA  208.0    18.0
102949         EEE             2014J             TMA  131.0    28.0

        module_presentation_length
21977                          268
161181                         261
13412                          240
21599                          268
102949                         269

In [11]:
# third merged is student specific VLE data + general VLE info + standard course
vle_data = datasets["student_vle"].merge(datasets["vle"], on=["id_site","code_module","code_presentation"],how="left")
vle_data = vle_data.merge(datasets["courses"], on=["code_module","code_presentation"], how="left")

print(vle_data.sample(5))

        code_module code_presentation  id_student  id_site  date  sum_click  \
5924509         EEE             2014J      611961   832658    19          8
9367265         FFF             2014J     1722493   882577    28         21
4031999         DDD             2013J      531402   673542   100          1
4775987         DDD             2014J     2025354   813701     0          1
5015456         DDD             2014J      402958   813711    92          3

        activity_type  week_from  week_to  module_presentation_length
5924509     oucontent        2.0      2.0                         269
9367265     oucontent        5.0      5.0                         269
4031999       forumng        NaN      NaN                         261
4775987      homepage        NaN      NaN                         262
5015456      glossary        NaN      NaN                         262

In [12]:
#final dataset is simply the vle resources, needed for final recommendations
resource_data = datasets["vle"].copy()

In [13]:
# wayy more organized, reduced 7 DFs to 4
merged_data = {"student_data": student_data, "assessment_data":assessment_data,"vle_data":vle_data, "resource_data": resource_data}

In [14]:
# handle duplicates, first observe

print("Student data number of duplicates:",merged_data["student_data"].duplicated().sum())
print("Assessment data number of duplicates:",merged_data["assessment_data"].duplicated().sum())
print("VLE data number of duplicates:",merged_data["vle_data"].duplicated().sum())
print("Resource data number of duplicates:",merged_data["resource_data"].duplicated().sum())

Student data number of duplicates: 0
Assessment data number of duplicates: 0
VLE data number of duplicates: 787170
Resource data number of duplicates: 0

In [15]:
# seemsl ike vle has a lot of duplicates, view percentage according to entire dataset 
print("Percentage of duplicates in VLE data", (merged_data["vle_data"].duplicated().sum()/len(merged_data["vle_data"]))*100)

Percentage of duplicates in VLE data 7.387605018357096

In [16]:
# final decision: not dropping VLE duplicates because it indicates possibly real multiple interactions 
# note that documentation on OULAD dataset does not mention duplicates
# will drop student/assessment data for completeness in the official python file, but leaving  VLE to be aggregated for resource interaction

In [17]:
# HANDLING MISSING VALUES

# student data

merged_data["student_data"].isna().sum()

code_module                       0
code_presentation                 0
id_student                        0
gender                            0
region                            0
highest_education                 0
imd_band                       1111
age_band                          0
num_of_prev_attempts              0
studied_credits                   0
disability                        0
final_result                      0
date_registration                45
date_unregistration           22521
module_presentation_length        0
dtype: int64

In [18]:
merged_data["student_data"]["imd_band"].mode()

0    20-30%
Name: imd_band, dtype: str

In [19]:
#  for imd band, will fill with mode because it is categorical data and it does not introduce bias
merged_data["student_data"]["imd_band"] = merged_data["student_data"]["imd_band"].fillna(merged_data["student_data"]["imd_band"].mode()[0])

In [20]:
merged_data["student_data"].isna().sum()

code_module                       0
code_presentation                 0
id_student                        0
gender                            0
region                            0
highest_education                 0
imd_band                          0
age_band                          0
num_of_prev_attempts              0
studied_credits                   0
disability                        0
final_result                      0
date_registration                45
date_unregistration           22521
module_presentation_length        0
dtype: int64

In [21]:
# for date registration, will drop because its only 45 records
merged_data["student_data"] = merged_data["student_data"].dropna(subset=['date_registration'])

merged_data["student_data"].isna().sum()

code_module                       0
code_presentation                 0
id_student                        0
gender                            0
region                            0
highest_education                 0
imd_band                          0
age_band                          0
num_of_prev_attempts              0
studied_credits                   0
disability                        0
final_result                      0
date_registration                 0
date_unregistration           22515
module_presentation_length        0
dtype: int64

In [22]:
# from research paper on dataset: 
# Students, who completed the course have this field empty. 
# Students who unregistered have Withdrawal as the value of the final_result in the studentInfo table.

# solution: create separate column with withdrawn boolean flag and fill date unregistration with the module length
merged_data["student_data"]["withdrew"] = merged_data["student_data"]["final_result"] == "Withdrawn"
merged_data["student_data"]["date_unregistration"] = merged_data["student_data"]["date_unregistration"].fillna(merged_data["student_data"]["module_presentation_length"])

In [23]:
merged_data["student_data"].isna().sum()

code_module                   0
code_presentation             0
id_student                    0
gender                        0
region                        0
highest_education             0
imd_band                      0
age_band                      0
num_of_prev_attempts          0
studied_credits               0
disability                    0
final_result                  0
date_registration             0
date_unregistration           0
module_presentation_length    0
withdrew                      0
dtype: int64

In [24]:
#next dataset to handle missing: assessment_data
merged_data["assessment_data"].isna().sum()

id_assessment                    0
id_student                       0
date_submitted                   0
is_banked                        0
score                          173
code_module                      0
code_presentation                0
assessment_type                  0
date                          2865
weight                           0
module_presentation_length       0
dtype: int64

In [25]:
# score will be dropped, very few records and risky to introduce bias in important feature
merged_data["assessment_data"] = merged_data["assessment_data"].dropna(subset=['score'])

In [26]:
merged_data["assessment_data"].isna().sum()

id_assessment                    0
id_student                       0
date_submitted                   0
is_banked                        0
score                            0
code_module                      0
code_presentation                0
assessment_type                  0
date                          2865
weight                           0
module_presentation_length       0
dtype: int64

In [27]:
#for missing dates, according to paper:
#If the information about the final exam cut-off day is missing, it takes place during the last week of the module-presentation.
merged_data["assessment_data"]["date"] = merged_data["assessment_data"]["date"].fillna(merged_data["assessment_data"]["module_presentation_length"]-7)

In [28]:
merged_data["assessment_data"].isna().sum()

id_assessment                 0
id_student                    0
date_submitted                0
is_banked                     0
score                         0
code_module                   0
code_presentation             0
assessment_type               0
date                          0
weight                        0
module_presentation_length    0
dtype: int64

In [29]:
#vle data for missing
merged_data["vle_data"].isna().sum()

code_module                         0
code_presentation                   0
id_student                          0
id_site                             0
date                                0
sum_click                           0
activity_type                       0
week_from                     9269544
week_to                       9269544
module_presentation_length          0
dtype: int64

In [30]:
# large nubmer of week from/to missing, will remove columns entirely as they are not critical to recommendation
merged_data["vle_data"] = merged_data["vle_data"].drop(columns=['week_from','week_to'])

In [31]:
merged_data["vle_data"].isna().sum()

code_module                   0
code_presentation             0
id_student                    0
id_site                       0
date                          0
sum_click                     0
activity_type                 0
module_presentation_length    0
dtype: int64

In [32]:
#last dataset for missing resources
merged_data["resource_data"].isna().sum()

id_site                 0
code_module             0
code_presentation       0
activity_type           0
week_from            5243
week_to              5243
dtype: int64

In [33]:
# large nubmer of week from/to missing, will remove columns entirely as they are not critical to recommendation
merged_data["resource_data"] = merged_data["resource_data"].drop(columns=['week_from','week_to'])

In [34]:
merged_data["resource_data"].isna().sum()

id_site              0
code_module          0
code_presentation    0
activity_type        0
dtype: int64

In [35]:
# next is fixing data types by typecasting

merged_data["student_data"].dtypes

code_module                       str
code_presentation                 str
id_student                      int64
gender                            str
region                            str
highest_education                 str
imd_band                          str
age_band                          str
num_of_prev_attempts            int64
studied_credits                 int64
disability                        str
final_result                      str
date_registration             float64
date_unregistration           float64
module_presentation_length      int64
withdrew                         bool
dtype: object

In [36]:
# convert categories columns:
student_categorical_columns = ["code_module","code_presentation","gender","region","highest_education","imd_band","age_band","final_result"]

for column in student_categorical_columns:
    merged_data["student_data"][column] = merged_data["student_data"][column].astype("category")

In [37]:
#convert booleans
merged_data["student_data"]["withdrew"] = merged_data["student_data"]["withdrew"].astype(bool)

#code inspiration from :https://stackoverflow.com/questions/43897296/pandas-converting-yes-no-to-true-false-failing
# replace y/n with true/false before typecast
merged_data["student_data"] =merged_data["student_data"].replace({'disability': {'Y': True, 'N': False}})
#end inspired code

merged_data["student_data"]["disability"] = merged_data["student_data"]["disability"].astype(bool)

In [38]:
#final data types
merged_data["student_data"].dtypes

code_module                   category
code_presentation             category
id_student                       int64
gender                        category
region                        category
highest_education             category
imd_band                      category
age_band                      category
num_of_prev_attempts             int64
studied_credits                  int64
disability                        bool
final_result                  category
date_registration              float64
date_unregistration            float64
module_presentation_length       int64
withdrew                          bool
dtype: object

In [39]:
#second is assessment data
merged_data["assessment_data"].dtypes

id_assessment                   int64
id_student                      int64
date_submitted                  int64
is_banked                       int64
score                         float64
code_module                       str
code_presentation                 str
assessment_type                   str
date                          float64
weight                        float64
module_presentation_length      int64
dtype: object

In [40]:
# convert categories columns:
assessment_categorical_columns = ["code_module","code_presentation","assessment_type"]

for column in assessment_categorical_columns:
    merged_data["assessment_data"][column] = merged_data["assessment_data"][column].astype("category")

In [41]:
#convert boolean
merged_data["assessment_data"]["is_banked"] = merged_data["assessment_data"]["is_banked"].astype(bool)

In [42]:
# final data types
merged_data["assessment_data"].dtypes

id_assessment                    int64
id_student                       int64
date_submitted                   int64
is_banked                         bool
score                          float64
code_module                   category
code_presentation             category
assessment_type               category
date                           float64
weight                         float64
module_presentation_length       int64
dtype: object

In [43]:
# vle data to typecast
merged_data["vle_data"].dtypes

code_module                     str
code_presentation               str
id_student                    int64
id_site                       int64
date                          int64
sum_click                     int64
activity_type                   str
module_presentation_length    int64
dtype: object

In [44]:
merged_data["vle_data"].sample(5)

,code_module,code_presentation,id_student,id_site,date,sum_click,activity_type,module_presentation_length
140343,AAA,2013J,2574528,546614,183,1,homepage,268
8282439,FFF,2013J,598835,716238,221,1,homepage,268
8154431,FFF,2013J,299281,716258,173,22,oucontent,268
1233681,BBB,2014B,97006,768351,6,2,homepage,234
7006424,FFF,2013B,418998,527261,163,3,url,240

In [45]:
# convert categories columns:
vle_categorical_columns = ["code_module","code_presentation","activity_type"]

for column in vle_categorical_columns:
    merged_data["vle_data"][column] = merged_data["vle_data"][column].astype("category")

In [46]:
#vle final data types
merged_data["vle_data"].dtypes

code_module                   category
code_presentation             category
id_student                       int64
id_site                          int64
date                             int64
sum_click                        int64
activity_type                 category
module_presentation_length       int64
dtype: object

In [47]:
#resources data types
merged_data["resource_data"].dtypes

id_site              int64
code_module            str
code_presentation      str
activity_type          str
dtype: object

In [48]:
# convert categories columns:
resource_categorical_columns = ["code_module","code_presentation","activity_type"]

for column in resource_categorical_columns:
    merged_data["resource_data"][column] = merged_data["resource_data"][column].astype("category")

In [49]:
#final resources data types
merged_data["resource_data"].dtypes

id_site                 int64
code_module          category
code_presentation    category
activity_type        category
dtype: object

In [50]:
#FEATURE ENGINEERING

In [51]:
#first for student data
merged_data["student_data"].sample(5)

,code_module,code_presentation,id_student,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,disability,final_result,date_registration,date_unregistration,module_presentation_length,withdrew
19735,EEE,2013J,560326,M,London Region,Lower Than A Level,40-50%,35-55,0,90,False,Withdrawn,-95.0,73.0,268,True
11544,CCC,2014J,585769,F,Scotland,Post Graduate Qualification,50-60%,0-35,1,60,False,Withdrawn,-72.0,130.0,269,True
22328,FFF,2013B,88957,M,South East Region,Lower Than A Level,30-40%,0-35,1,120,False,Withdrawn,-137.0,-2.0,240,True
30540,GGG,2013J,589377,F,North Western Region,A Level or Equivalent,20-30%,0-35,0,30,False,Distinction,-38.0,261.0,261,False
4998,BBB,2014B,423652,F,East Anglian Region,Lower Than A Level,70-80%,0-35,0,120,True,Distinction,-29.0,234.0,234,False

In [52]:
#obtain registration duration
merged_data["student_data"]["registration_duration"] = merged_data["student_data"]["date_unregistration"] - merged_data["student_data"]["date_registration"]

In [53]:
#for assessment
merged_data["assessment_data"].sample(5)

,id_assessment,id_student,date_submitted,is_banked,score,code_module,code_presentation,assessment_type,date,weight,module_presentation_length
140920,34895,413200,228,False,74.0,FFF,2014B,CMA,227.0,0.0,241
97818,30711,528083,124,False,83.0,EEE,2013J,TMA,124.0,28.0,268
47784,24283,633447,101,False,91.0,CCC,2014B,TMA,102.0,22.0,241
161532,37418,401139,94,False,100.0,GGG,2013J,CMA,229.0,0.0,261
53507,24290,418623,236,False,82.0,CCC,2014B,Exam,234.0,100.0,241

In [54]:
#average score of student for course across all assessments
average_scores = merged_data["assessment_data"].groupby(["id_student", "code_module","code_presentation"])["score"].mean()

#will rename index so that its clear when merged with final df
average_scores = average_scores.reset_index(name="average_score")

In [55]:
average_scores.sample(5)

       id_student code_module code_presentation  average_score
2548       313937         AAA             2014J      80.800000
7392       527393         BBB             2013J      72.000000
18834      634246         DDD             2014B      56.333333
25688     2677097         DDD             2013J      72.428571
71          32885         AAA             2013J      54.400000

In [56]:
merged_data["assessment_data"][merged_data["assessment_data"]["id_student"] ==575112]

,id_assessment,id_student,date_submitted,is_banked,score,code_module,code_presentation,assessment_type,date,weight,module_presentation_length
142549,34899,575112,23,False,84.0,FFF,2014J,TMA,24.0,12.5,269
144728,34900,575112,50,False,72.0,FFF,2014J,TMA,52.0,12.5,269
146849,34901,575112,91,False,88.0,FFF,2014J,TMA,94.0,25.0,269
147359,34902,575112,135,False,86.0,FFF,2014J,TMA,136.0,25.0,269
148913,34903,575112,197,False,93.0,FFF,2014J,TMA,199.0,25.0,269
150740,34904,575112,65,False,91.0,FFF,2014J,CMA,241.0,0.0,269
151259,34905,575112,107,False,89.0,FFF,2014J,CMA,241.0,0.0,269
152901,34906,575112,132,False,68.0,FFF,2014J,CMA,241.0,0.0,269
154664,34907,575112,156,False,91.0,FFF,2014J,CMA,241.0,0.0,269
155106,34908,575112,170,False,75.0,FFF,2014J,CMA,241.0,0.0,269
156592,34909,575112,226,False,78.0,FFF,2014J,CMA,241.0,0.0,269
158297,34910,575112,177,False,88.0,FFF,2014J,CMA,241.0,0.0,269

In [57]:
# simply verifying that it works
merged_data["assessment_data"][merged_data["assessment_data"]["id_student"] ==575112]["score"].mean()

np.float64(83.58333333333333)

In [58]:
#merge with final
merged_data["assessment_data"] = merged_data["assessment_data"].merge(average_scores, on=["id_student", "code_module","code_presentation"],how="left")

In [59]:
merged_data["assessment_data"].sample(5)

,id_assessment,id_student,date_submitted,is_banked,score,code_module,code_presentation,assessment_type,date,weight,module_presentation_length,average_score
58218,24295,685572,21,False,78.0,CCC,2014J,CMA,18.0,2.0,269,71.428571
44806,15023,649742,152,False,63.0,BBB,2014J,TMA,152.0,35.0,262,70.000000
66912,25335,560260,51,False,67.0,DDD,2013B,TMA,53.0,10.0,240,76.692308
126157,34880,86669,53,False,80.0,FFF,2013J,CMA,236.0,0.0,268,84.166667
159805,37416,597058,120,False,80.0,GGG,2013J,TMA,124.0,0.0,261,86.875000

In [60]:
# third is resource data

#resource text used for content based filtering
merged_data["vle_data"].sample(5)

,code_module,code_presentation,id_student,id_site,date,sum_click,activity_type,module_presentation_length
600073,BBB,2013B,506753,542893,100,1,quiz,240
9169130,FFF,2014J,549847,882665,3,2,oucontent,269
1625402,BBB,2014J,649189,926333,42,1,quiz,262
3517457,DDD,2013B,540207,547557,130,2,ouwiki,240
2716685,CCC,2014J,633960,909092,66,37,quiz,269

In [61]:
merged_data["resource_data"]["resource_text"] = merged_data["vle_data"]["code_module"].astype(str) + " " + merged_data["vle_data"]["code_presentation"].astype(str) + " " + merged_data["vle_data"]["activity_type"].astype(str)

In [62]:
merged_data["resource_data"].sample(5)

      id_site code_module code_presentation activity_type        resource_text
835    704182         BBB             2013J      resource   AAA 2013J resource
5385   779482         FFF             2014B      resource   AAA 2013J homepage
4441   527483         FFF             2013B      resource  AAA 2013J oucontent
2462   673534         DDD             2013J       forumng    AAA 2013J subpage
645    543231         BBB             2013B      resource  AAA 2013J oucontent

In [63]:
#FINAL PREPROCESSING: create resource interaction df for VLE interaction aggregation (so total dfs used will be 5)

In [64]:
merged_data["vle_data"].sample(5)

,code_module,code_presentation,id_student,id_site,date,sum_click,activity_type,module_presentation_length
163621,AAA,2013J,114999,546686,221,1,oucontent,268
3894175,DDD,2013J,2382048,673537,39,1,forumng,261
977756,BBB,2013J,613208,703732,94,5,forumng,268
9700227,FFF,2014J,646460,882996,99,1,resource,269
3129985,DDD,2013B,2479086,547627,-15,1,resource,240

In [65]:
#code inspired by: https://www.kaggle.com/code/veenajoe/veena-vit-project-msc-ds-june-2026#4.2-Aggregating-students-based-on-id

#grouped so each row has one student and their intercation with 1 module resource, each aggregation column specifies 
# new columnName =  (column from VLE data used in aggregation, aggregation function)
#main feature used for collaboartive filtering is the total resource clicks
interaction_data = merged_data["vle_data"].groupby(["id_student","code_module","code_presentation","id_site","activity_type"]).agg(total_resource_clicks=("sum_click","sum"),first_used=("date","min"),last_used=("date","max")).reset_index()
#end inspired code

In [66]:
interaction_data.sample(5)

,id_student,code_module,code_presentation,id_site,activity_type,total_resource_clicks,first_used,last_used
1456314,643568,CCC,2014J,909237,subpage,2,230,230
1537386,654414,DDD,2014J,814158,resource,2,66,66
455523,493539,FFF,2013J,716325,oucontent,71,27,32
1430272,636594,DDD,2014J,814084,resource,1,-15,-15
1634716,685370,EEE,2014J,832672,oucontent,11,104,107

In [67]:
#verifying no missing
interaction_data.isna().sum()

id_student               0
code_module              0
code_presentation        0
id_site                  0
activity_type            0
total_resource_clicks    0
first_used               0
last_used                0
dtype: int64

In [70]:
interaction_data.loc[interaction_data['total_resource_clicks'].idxmax()]

id_student                540184
code_module                  BBB
code_presentation          2013B
id_site                   542807
activity_type            forumng
total_resource_clicks       8837
first_used                     0
last_used                    240
Name: 627011, dtype: object

In [72]:
#verifies that id site is globally unique, can use simple user-item matrix for collaborative filtering instead of composite key
interaction_data.groupby("id_site")[["code_module", "code_presentation", "activity_type"]].nunique().max()

code_module          1
code_presentation    1
activity_type        1
dtype: int64

In [74]:
#looking at values for temporal splitting (evaluation)
merged_data["vle_data"].sample(5)

,code_module,code_presentation,id_student,id_site,date,sum_click,activity_type,module_presentation_length
7288542,FFF,2013J,368315,716238,1,17,homepage,268
7325390,FFF,2013J,601271,716216,5,3,forumng,268
9062226,FFF,2014J,650866,882923,-18,1,resource,269
10588630,GGG,2014J,591755,896943,106,7,homepage,269
3887794,DDD,2013J,570896,673519,37,2,homepage,261

In [75]:
interaction_data.sample(5)

,id_student,code_module,code_presentation,id_site,activity_type,total_resource_clicks,first_used,last_used
1124025,601951,BBB,2013J,703940,subpage,2,36,93
1470117,645880,FFF,2014J,883302,dataplus,1,241,241
103405,190653,FFF,2013B,527117,questionnaire,3,33,33
1600138,680414,DDD,2014J,814284,url,1,30,30
1003115,589554,BBB,2014J,913533,oucontent,1,107,107

In [77]:
#median number of days, used for cutoff day in temporal splitting
merged_data["vle_data"]["date"].median()

np.float64(86.0)

In [78]:
#checking if this needs splitting, as per output no need as it is simply a list of resources
merged_data["resource_data"].sample(5)

,id_site,code_module,code_presentation,activity_type,resource_text
1830,909098,CCC,2014J,quiz,AAA 2013J forumng
3460,814017,DDD,2014J,subpage,AAA 2013J forumng
5497,779584,FFF,2014B,resource,AAA 2013J oucontent
4119,527127,FFF,2013B,questionnaire,AAA 2013J homepage
2236,547930,DDD,2013B,subpage,AAA 2013J oucontent

In [88]:
#checking evaluation functions, copied from .py file for further analysis
def temporal_split(vle_data,cutoff_day):

    history_vle = vle_data[vle_data["date"]<=cutoff_day].copy()
    future_vle = vle_data[vle_data["date"]> cutoff_day].copy()

    #SAME AS PREPROCESSING STEP for interaction data
    #code inspired by: https://www.kaggle.com/code/veenajoe/veena-vit-project-msc-ds-june-2026#4.2-Aggregating-students-based-on-id

    #grouped so each row has one student and their intercation with 1 module resource, each aggregation column specifies 
    # new columnName =  (column from VLE data used in aggregation, aggregation function)
    #main feature used for collaboartive filtering is the total resource clicks
    history_interactions = history_vle.groupby(["id_student","code_module","code_presentation","id_site","activity_type"]).agg(total_resource_clicks=("sum_click","sum"),first_used=("date","min"),last_used=("date","max")).reset_index()
    future_interactions = future_vle.groupby(["id_student","code_module","code_presentation","id_site","activity_type"]).agg(total_resource_clicks=("sum_click","sum"),first_used=("date","min"),last_used=("date","max")).reset_index()

   #end inspired code

    #to store in 2 separate variables during evaluaton
    return (history_interactions, future_interactions)

#KEY EVALUATION METRICS, input is pandas series of relevant/recommended id of resources
#code copied from: https://giorgi.tech/blog/offline-metrics-for-recommender-systems/
def precision_k(relevant, recommended,k):
    return len(set(relevant).intersection(recommended[:k])) /k

def recall_k(relevant, recommended, k):
    return len(set(relevant).intersection(recommended[:k])) / len(relevant)

#end copied code

In [98]:
history_interactions, future_interactions = temporal_split(merged_data["vle_data"],86)
evaluated_student = 11391

#items from interactions
history_items = history_interactions[history_interactions["id_student"]==evaluated_student]["id_site"]
future_items = future_interactions[history_interactions["id_student"]==evaluated_student]["id_site"]

#removed used resources in history from future items, as goal is to recommend new items
relevant_items = future_items[~future_items.isin(history_items)].unique()

print(len(relevant_items))

37

/var/folders/lg/2w3dsv0s5ll7bp5v9gm83hm80000gn/T/ipykernel_82425/3326403485.py:6: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  future_items = future_interactions[history_interactions["id_student"]==evaluated_student]["id_site"]

In [100]:
#seeing how many students can be evaluated (before filtering for historical/future interactions)
len(interaction_data["id_student"].unique())

26074